### ISSUE TITLE
myShuffleInstance.layout() with imagesloaded plugin help

### ISSUE THREAD

**Issue by blamejen** [Vestride/Shuffle#100]
Hi 
I am trying to get working with imagesloaded with shufflejs.
[Image example](https://vestride.github.io/Shuffle/images) #solution3
Currently I am using code as below. 
From the code, how can I add imagesloaded? Any examples?
I am using shufflejs with webpack.
Thank you for any help!
```
var Grid = function (element) {
  this.element = element;

  this.shuffle = new Shuffle(element, {
    itemSelector: '.item',
    sizer: element.querySelector('.my-sizer-element')
  });

  this._activeFilters = [];
  this.addFilterButtons();
  this.addSorting();
  this.addSearchFilter();
};
```

**Comment by Vestride** [comment]
Please review the [documentation for imagesloaded](http://imagesloaded.desandro.com/). In your callback, you will want to call `this.shuffle.layout()`

**Comment by blamejen** [comment]
Thanks! I added 'imagesloaded' callback function
```
var Grid = function (element) {
  this.element = element;
  this.shuffle = new Shuffle(element, {
    itemSelector: '.item',
    sizer: element.querySelector('.my-sizer-element')
  });
  var imgLoad = imagesLoaded(element);
  imgLoad.on('always',this.onAlways);
};
Grid.prototype.onAlways = function(instance) {
	console.log('all images are loaded');
	this.shuffle.layout();
};
```
However there is an error:
`Uncaught TypeError: Cannot read property 'layout' of undefined`

**Comment by Vestride** [comment]
That is because inside your `onAlways` method, `this` is not the same `this` as inside the first function (constructor) where you assign `this.shuffle` equal to something. To solve this, use [Function.prototype.bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind). This is an important concept to understand in JavaScript.

**Comment by blamejen** [comment]
Solved by
`imgLoad.on('always',this.onAlways.bind(this));`
Thanks!
