### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#101]
I'm trying to use Shuffle in a simple way, and sometimes it works, sometimes it doesn't. I have a grid with videos and each has `data-group` set (sometimes with two group strings). When I try to filter, it's hiding the elements completely. 

```
  videoCollection = new Shuffle($('#grid').get(0), {
    itemSelector: '.training__video',
    sizer: '.my-sizer-element'
  });
```

**Comment by cameronroe** [comment]
Ah, I see that I was using the filter method with a string. My mistake.

**Comment by Vestride** [comment]
You should be able to filter by a string. For example, if you open the console on the home page and entery:

```js
demo.shuffle.filter('photography')
```

It will display items with `data-groups` that have `"photography"`
