### ISSUE TITLE
Issue in Safari 7.0.0.

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#102]
Latest Chrome
![screen shot 2016-05-03 at 5 40 20 pm](https://cloud.githubusercontent.com/assets/1614348/14999285/415e5fd4-1156-11e6-923a-200c2764fad9.png)

Safari 7
![screen shot 2016-05-03 at 5 40 10 pm](https://cloud.githubusercontent.com/assets/1614348/14999284/415a377e-1156-11e6-8566-a244035c8bdb.png)

The elements get positioned absolutely on top of each other.

**Comment by Vestride** [comment]
It won't work in Safari 8 either because it doesn't have unprefixed transforms. You can either opt out of transforms with the `useTransforms` option set to false or downgrade to version 3 of shuffle.

http://caniuse.com/#feat=transforms2d
