### ISSUE TITLE
Doesn't work with flexbox grids

### ISSUE THREAD

**Issue by ShaMSofT** [Vestride/Shuffle#103]
Hi,

It seems Shuffle.js doesn't work with flexbox!

I tried Bootstrap v4.0 on your [bootstrap demo](https://vestride.github.io/Shuffle/bootstrap3-grid). The default release works fine, but if you build it using enabled flexbox grid, Shuffle.js won't work anymore.
Here is flex-enabled bootstrap 4.0: [bootstrap.min.zip](https://github.com/Vestride/Shuffle/files/275739/bootstrap.min.zip). You can simply replace it with bootstrap.min.css in your demo.

Any idea on how to fix it?

**Comment by Vestride** [comment]
When using a flexbox grid, you will also need to specify a `width` for each column because Shuffle absolutely positions items.

I created a jsbin demo to help me debug the issue which you can see here: http://jsbin.com/disuroz/4/edit?html,css,js,output
