### ISSUE TITLE
Ready/complete event or callback

### ISSUE THREAD

**Issue by joemaller** [Vestride/Shuffle#104]
It would be great if we could specify a `ready` callback in options, or if there was a `complete` event on the Shuffle object. Either of these would allow us to know when the new shuffle instance was finished initializing.

At it's simplest, this would allow us to have more control over layout-thrashing if we choose to have the initial shuffle view filtered or sorted in some way that differs from the html. 

Is there some other recommended way of responding when the shuffle instance is done setting itself up?

(one other option is to style based on the `shuffle` class that's added to the container, but because Shuffle directly applies styles, we're limited in what we can do without a mess of `!important` overrides.)

**Comment by Vestride** [comment]
Instantiating shuffle is synchronous, so there's no need for a `complete` event/callback. If you wish to initialize the instance with an initial sort or filter, you can use the `initialSort` and `group` options.

**Comment by joemaller** [comment]
Excellent, thanks for the explanation!
