### ISSUE TITLE
No ES6 message

### ISSUE THREAD

**Issue by kimek** [Vestride/Shuffle#105]
Hi Glen
I just have out of topic question about general not supporting browser 'below' ES6. I've visited your script on Safari 8 (Iphone5) and all items are positioned on left top corner, one on top of each other. 
I've run also your script on babelify and same issue appear. 

Is this is an issue or this is just not supporting 'old' browsers ? If second answer, why most of the script now-a-days don't have a msg to inform that they not working on particular browsers (as babelify have also limits on transfering es6 to es5) ?  

Thanks Glen

**Comment by Vestride** [comment]
#102
