### ISSUE TITLE
Filtering for non-JSON data-groups

### ISSUE THREAD

**Issue by NazarkinRoman** [Vestride/Shuffle#108]
Hi.

Today I have faced next bug: when you're trying to use `delimeter` option in order to pass values to `data-groups` as a string - Shuffle throws JSON parsing error.

This makes filtering impossible. The error in that:

- attribute text being parsed without any checks
- in `_doesPassFilter` function use `this.delimeter` variable, which actually located in `this.options` object

I have patched code of `_doesPassFilter` function:

	_doesPassFilter(category, element) {
	
		if (typeof category === 'function') {
			return category.call(element, element, this);
		
		// Check each element's data-groups attribute against the given category.
		} else {
			let attr = element.getAttribute('data-' + Shuffle.FILTER_ATTRIBUTE_KEY);
			let keys = attr.split(this.options.delimeter);
			if(!this.options.delimeter) keys = JSON.parse(attr);
		
			if (Array.isArray(category)) {
				return category.some(arrayIncludes(keys));
			}
		
			return arrayIncludes(keys, category);
		}
	}

Hope to see this fix in a master branch. :)

**Comment by Vestride** [comment]
Fixed in `v4.0.1`
