### ISSUE TITLE
Call shuffle from Wordpress Customizer

### ISSUE THREAD

**Issue by chozze** [Vestride/Shuffle#109]
Hello, I'm having issues calling Shuffle methods (layout, update) from Wordpress Customizer, I tried calling window.shuffle.layout, iframes, parent iframe..don't know how to call it correctly, this is my shuffle registration from main js file:

```js
(function($) {
  "use strict";
  var niteo = niteo || {};

  $(document).ready(function() {
    niteo.shuffleGallery();
  });

  niteo.shuffleGallery = function() {
    var element = document.getElementById('gallery'),
        gutter = $('#gallery').data('gutter'),
        Shuffle = window.shuffle,
        shuffle;

    // instantiate the plugin
    $('#gallery').imagesLoaded(function() {
      shuffle = new Shuffle(element, {
        itemSelector: '#gallery .gal-item',
        gutterWidth: gutter
      });
    });
  }
}
```

any idea? thanks

**Comment by Vestride** [comment]
Your code looks fine to me. I don't know what WordPress Customizer is though. If you had a demo I might be able to help. See [CONTRIBUTING.md](https://github.com/Vestride/Shuffle/blob/master/CONTRIBUTING.md#submitting-issues) for more information.

**Comment by chozze** [comment]
It is a native Wordpress function. But basically its just calling a js function from another js file. So I need to call shuffle from parent`s iframe (where shuffle is declared) js file.

thanks Alex

**Comment by Vestride** [comment]
I suggest making sure that other JavaScript code works inside your iframe, then try to get Shuffle to work. Without any more information, I can't help you.
