### ISSUE TITLE
v4.0 Not working for me

### ISSUE THREAD

**Issue by gazpachu** [Vestride/Shuffle#110]
There are no errors. Everything seems to be fine but the DOM elements are not being animated and rearranged when resizing the window

![screen shot 2016-07-20 at 14 34 01](https://cloud.githubusercontent.com/assets/1721288/16988087/24d5401c-4e87-11e6-8819-8fcf7c4e0022.png)

At the same time, I've noticed that the documentation is lacking CSS for the basic example. I read that the CSS is being injected? Maybe this needs a further clarification...

**Comment by Vestride** [comment]
There is no required CSS.

Your issue is likely because you're using images.
