### ISSUE TITLE
Add webkit-prefixed transforms

### ISSUE THREAD

**Issue by joemaller** [Vestride/Shuffle#115]
I recently implemented visual regression testing on a site which uses Shuffle. We ran into an problem where Phantom.js would not render the Shuffle grids correctly.

There's a simple, one-line fix for this, but it's a bit of an edge case so I wanted to run it by you first. 

The version of Webkit in PhantomJS still requires vendor-prefixed transforms. Safari required `-webkit-` prefixed CSS 3 transforms until version 9 was released in September 2015. ([1], [2])

The following addition to `src/shuffle.js` adds Webkit-prefixed transform rules to the element:

[lines 618-623](https://github.com/Vestride/Shuffle/blob/13d3dacc772f49244da331b3f1271b7ad0e26614/src/shuffle.js#L618-L623):
```javascript
    if (this.options.useTransforms) {
      styles.transform = `translate(${x}px, ${y}px) scale(${item.scale})`;
      styles.webkitTransform = `translate(${x}px, ${y}px) scale(${item.scale})`;
    } else {
      styles.left = x + 'px';
      styles.top = y + 'px';
    }
```
This only adds functionality, there are no negative side-effects as vendor prefixes are ignored by other browsers. While only a small subset of browsers are affected, this addition would be exceptionally useful for testing. As there are no side-effects, it doesn't seem worth making this a configuration setting.

[1]: http://caniuse.com/#feat=transforms2d
[2]: https://en.wikipedia.org/wiki/Safari_version_history

**Comment by Vestride** [comment]
Hey there.

I likely will not add the WebKit prefix. You have 4 options to fix this, ordered from what I believe is the easiest to most time consuming:

1. Set useTransforms to false for browsers which don't support unprefixed transforms.
2. Create a subclass of Shuffle and override the _getStylesForTransition method to add the prefixed property.
3. Downgrade to Shuffle v3.
4. Fork Shuffle.

Duplicates: #102 #105

**Comment by Vestride** [comment]
Also, thanks for the well-written issue :]

**Comment by joemaller** [comment]
Totally understood. Thanks for the ideas about how to work around this. 

For anyone else who googles themselves here, I ended up extending Shuffle and overriding both `_getStylesForTransition` and `_setTransitions`. Our Shuffle grids are now working with PhantomJS (for visual regression testing with BackstopJS) and older WebKit browsers. Here's my code:

```javascript
const ShuffleJS = require('shufflejs');
class Shuffle extends ShuffleJS {
  _getStylesForTransition(args) {
    let styles = super._getStylesForTransition(args);
    if (styles.transform) {
      styles.webkitTransform = styles.transform;
    }
    return styles;
  }

  _setTransitions(items = this.items) {
    let speed = this.options.speed;
    let easing = this.options.easing;

    var str;
    if (this.options.useTransforms) {
      str = 'transform ' + speed + 'ms ' + easing +
        ', opacity ' + speed + 'ms ' + easing;
    } else {
      str = 'top ' + speed + 'ms ' + easing +
        ', left ' + speed + 'ms ' + easing +
        ', opacity ' + speed + 'ms ' + easing;
    }

    items.forEach((item) => {
      item.element.style.transition = str;
      item.element.style.webkitTransition = str.replace(/(transform)/, '-webkit-$1');
    });
  }
}
```

note:  The `forEach` in `_setTransitions` is asynchronous, copy-pasting the whole method was faster/lighter than wrapping it in a promise even though the override only adds a single line.

**Comment by Vestride** [comment]
Thanks for sharing!
