### ISSUE TITLE
Images not showing in chrome

### ISSUE THREAD

**Issue by umairrazzaq** [Vestride/Shuffle#123]
Hi, first of all its brilliant plugin I've used it on one my commercial project. Although I'm facing strange issue which mostly likely causing in -webkit- (chrome) browser.

I've used it in Bootstrap 3+ framework, I know it sounds strange but mostly (not every time) on load, the images wont show up. But as soon as i click on any filter button than all images will show up and sort.

**Comment by Vestride** [comment]
Please try searching next time. https://vestride.github.io/Shuffle/images

#98 #97 #80 #78 #50

**Comment by umairrazzaq** [comment]
Hello Vestride thanks for the message, i did do searching before asking here, but i never landed on your mentioned link nor any forum lead to me there.
