### ISSUE TITLE
How I can append New Items 

### ISSUE THREAD

**Issue by Vanthemes** [Vestride/Shuffle#124]
Hi,

Thank you for the great plugin.

I want to append new items to shuffle container using ajax, but the shuffle.update(),  shuffle.layout() does not update the grid with the new items, I don't want use Add() ( by the way this function caused an error in console: Cannot read property 'add' of undefined.. ), So because it need an array of new elements.

This is my code:

```
jQuery(document).ready(function($) {
	var $grid= $('#grid'),
	Shuffle = window.shuffle,
	shuffle;

	shuffle = new Shuffle( $grid, {
		itemSelector: '.item',
		sizer: '.item',
		delimeter: ' ',
	});

	$('#loadmore').bind('click',function(e){
		
		var page = 1,
		max     = 3;


		if ( page < max ) {

			$.post(ajaxUrl, {
				page: page,
				max: max     
			},function( data ){

				var $items = $(data);
				
				if( $items.length ){

					// Append the new elements
					$grid.append( $items );

					//  shuffle.update();  not working!
					//   shuffle.add($items); not working!

				} 

			});

		}
	});

});
```

Any help would be appreciated . Thanks.

**Comment by Vestride** [comment]
You should be passing a regular element as the first parameter to `new Shuffle(regularElement, options)`, not a jQuery-wrapped element.

Check out the [source for the adding and removing demo](https://github.com/Vestride/Shuffle/blob/master/js/demos/adding-removing.js)
