### ISSUE TITLE
Documentation not enough to get started

### ISSUE THREAD

**Issue by adammpkins** [Vestride/Shuffle#127]
.

**Comment by Vestride** [comment]
It seems you were able to figure out whatever was blocking you. Would you mind telling me what that was?

**Comment by adammpkins** [comment]
I removed my issue after some reflection. I decided that it sounded to
aggressive and accusatory for an issue. I apologize for being too forward.

Unfortunately, I wasn't able to get past what was impeding me, and I'm
trying isotope right now.


Can I recommend that you consider writing a very basic "Getting Started"
document which lays out every necessary step for installation and usage?

When integrating something like this, I want to be able to say to myself "I
did exactly what the documentation told me to, and received the same
results," or "I did what the docs said and I'm not getting the same results
as his demo, what did I read wrong or implement wrong?" When working with
shuffle yesterday, to get started, I implemented your html snippet at
https://vestride.github.io/Shuffle/, then got lost in the javascript
documentation immediately.

What I wanted the whole time was something that explained all of the steps
at once. Even some of your code pen demos seem to pull in different jquery
dependencies that aren't listed on the front page demo.

Do I need debounce? Tell me it's a dependency? Do I need the throttle
plugin to do what your demo did? It should be on the demo page.

Sorry that's not a simple fix, but the issue is the documentation. When
writing it you should have the expectation that your audience has basic
css, js and html skills, but hold their hand through a basic implementation.
