### ISSUE TITLE
simplify css

### ISSUE THREAD

**Issue by Matheo13** [Vestride/Shuffle#136]
Hi,

Thanks for your work but I can't use it right now.
Maybe I missed something but there is too much stuff inside styles.css, for instance if you already have bootsrap.
Only one css file to import would be nice as well. (should i import prism? What is it?)

Thank you again.

**Comment by Vestride** [comment]
To use Shuffle, you don't need any of the style sheets used in the demos.
If the main shuffle element does it have position relative or overflow
hidden, those will be added to the inline styles.
