### ISSUE TITLE
Support IE9 in v4

### ISSUE THREAD

**Issue by nashwaan** [Vestride/Shuffle#137]
First of all, thank you for the efforts and sharing this AWESOME library.
Great job @vestride       👍 

I see you clearly mentioned that this library supports IE >= 11.

You also mentioned that:

> Support for other browsers may be added with polyfills for ES5 features. If you require broader browser support, use the most recent v3 release of Shuffle.

I still want to use v4 version because of these appealing changes:
> v4.0.0 4/20/16 - Rewrite in ES6 with babel. Remove jQuery and Modernizr dependencies. Remove support for IE<11. Docs improvements. Switch to gulp build system with webpack.

Now, in my case, Shuffle v4 works perfectly in IE >= 10 (Perhaps due to babel-polyfills). It is somehow broken in IE9, though. Can you point me how to make it work in IE9? Does it depend on specific feature or needs specific polyfills?

**Comment by Vestride** [comment]
I don't have an IE9 VM, but I created a pen that works in IE11's IE9 emulator.

https://codepen.io/Vestride/pen/dvExbg

Basically:
* Needs a [`classList`](https://cdn.jsdelivr.net/classlist/2014.01.31/classList.min.js) polyfill.
* Set `useTransforms` option to `false`. v4 uses transforms and transitions without prefixes.
* Set `speed` option to `0`.

But that might not be all that needs to be fixed. Your mileage may vary. If that doesn't work for you, you'll have to downgrade versions, or look into [isotope v2](http://isotope.metafizzy.co/extras.html#browser-support) or [packery v1](http://packery.metafizzy.co/extras.html#browser-support).

**Comment by nashwaan** [comment]
Thanks @Vestride 

In my case, using `useTransforms: false` was enough to get it working for IE9!
 👍

**Comment by banoresaurabh** [comment]
@Vestride  I am trying to make shuffle js work on IE10 but I am getting a syntax error on class declaration syntax. I was wondering if there exists any polyfill that I am missing?
Furthermore, downgrading the version to 3.1.1 giving an error `this.shuffle.on is not a function`
