### ISSUE TITLE
appending items 

### ISSUE THREAD

**Issue by krystyna93** [Vestride/Shuffle#139]
Hi,

I wanted to ask, when appending items (https://vestride.github.io/Shuffle/adding-removing) to the shuffle grid via the append button, I notice that it appends infinite number of items when the button is clicked. 
Is this working the same as the 'load more' method in itself, and if so, does it only append with only the amount of items(images) I would have stored? I hope this makes sense.

Just need to clarify this point. Thanks.

**Comment by Vestride** [comment]
Like the demo shows, you need to add the elements to the shuffle grid, then tell your shuffle instance about the new items with `add()`

```js
/**
 * Create some DOM elements, append them to the shuffle container, then notify
 * shuffle about the new items. You could also insert the HTML as a string.
 */
Demo.prototype.onAppendBoxes = function () {
  var items = this._getArrayOfElementsToAdd();

  items.forEach(function (item) {
    this.element.appendChild(item);
  }, this);

  // Tell shuffle items have been appended.
  // It expects an array of elements as the parameter.
  this.shuffle.add(items);
};
```

I don't know what "items(images)" you "would have stored". Shuffle does not perform any ajax operations to fetch new data, you have to tell it that new elements are in its container.
