### ISSUE TITLE
Scaling Effect CSS

### ISSUE THREAD

**Issue by ndimatteo** [Vestride/Shuffle#140]
In the docs you mention:

> You can also customize the scaling effect with visible or hidden items, however, the `VISIBLE` and `HIDDEN` values _cannot_ be the exact same.

Why? I set the `HIDDEN` value to the same and it works fine, just without the scaling effect. I'd like to have a simple fade in/out effect and this seems to do the trick, but I'm curious why this is explicitly called out in the docs as something not to do?

----
**Shuffle Version:** 4.0

**Comment by Vestride** [comment]
The reaso you can't set them to the same value is that, internally, each item stores its scale and position. The scale and position are then used to determine whether there will be a transition, or if the item will stay the same ([see _layout](https://github.com/Vestride/Shuffle/blob/master/src/shuffle.js#L493)).
If the item is not going to move or scale, a transitionend event will never be dispatched.

What you can do is to set the hidden and visible values to be very close to each other. If you don't want them to scale, you could leave VISIBLE as 1 and set HIDDEN to 0.999.
