### ISSUE TITLE
iPad issues

### ISSUE THREAD

**Issue by adamgilmour** [Vestride/Shuffle#145]
Hi, I've tested your plugin on an iPad with the latest iOS version and unfortunately it doesn't seem to be displaying grid items correctly for me.
I've implemented the same functionality as shown on your home page demo with the button filtering, but it seems to only show one grid item at a time.

Testing the plugin home page demo also seems to have a few issues on iPad.

**Comment by Vestride** [comment]
Works for me in the iOS 10.3 simulator. Can you be more specific about what the issue is or what version of Safari you're using?

Could be related to #102

**Comment by adamgilmour** [comment]
Yeah, think it may be related.
Tested on an iPad mini iOS 8.4 and browserstack. Screenshot posted below.

![bs_realios_tablet_ipad air 2-8 0](https://cloud.githubusercontent.com/assets/13436050/25889773/f3cab2b8-3562-11e7-93ba-802596c01e2a.jpg)

It works fine > iOS 9 so I'll close this issue
