### ISSUE TITLE
Max filtered items 

### ISSUE THREAD

**Issue by svanskivar** [Vestride/Shuffle#146]
Hi, 

how many items can I max filter or sort with Shuffle.js? This is very important for me, because with isotope.js are only under 100 items recommended. 

best regards

**Comment by Vestride** [comment]
There is no maximum, but you will probably see degraded performance in some browsers will many items.

You might be able to get an idea of the performance if you visit the [adding and removing](https://vestride.github.io/Shuffle/adding-removing) demo and a lot.
