### ISSUE TITLE
Height Calculation in desktop Safari when @font-face is used

### ISSUE THREAD

**Issue by davidfwall** [Vestride/Shuffle#147]
I came across an issue – only affecting Safari on desktop (latest version) where using fonts brought in via @font-face made blocks in a Shuffle grid too tall. I think it might have been an issue in the timing of the font loading late, causing the calculation to be off. 

Anyway, I found a solution: loading the fonts via the Google / Typekit Web Font Loader instead–
https://github.com/typekit/webfontloader

**Comment by Vestride** [comment]
I think you're correct, the font loads after the javascript has been executed, causing calculations to be off, similar to [using images with Shuffle](https://vestride.github.io/Shuffle/images).

There are a few font loading techniques you could use to determine when your fonts are completely loaded, like typekit's loader. I have used [fontfaceobserver](https://github.com/bramstein/fontfaceobserver) in the past.

@davidfwall if you add an event listener to the window's `load` and call `myShuffleInstance.layout()`, does that work as well?
