### ISSUE TITLE
Is 'addToEnd' feature removed in v4.x?

### ISSUE THREAD

**Issue by Joseph7451797** [Vestride/Shuffle#148]
### Shuffle version

4.2.0

### What is Expected?

In version 3.1.1, there is an option of appended methed. For example:
```js
// If the third argument is 'true'(boolean), the new items will append to container and appear just behind the last child in container(in DOM structure) one by one.
$grid.shuffle('appended', $items, this.addToEnd);

```

### What is actually happening?

Now in version 4.2.0, new items always appear at position of the first child in container then move to the right place. It looks wired. I am wondering if I miss some setting or new api no longer supports this feature.

**Comment by Vestride** [comment]
Yes, that was removed. Now when you add items, they are mixed in with the current sorting.

I agree that it does look a little weird having them all come from `0, 0` though.
