### ISSUE TITLE
After Updating into Bootstrap 4 Portfolio isn't working

### ISSUE THREAD

**Issue by Hayko1994** [Vestride/Shuffle#152]
Hi. Before the update portfolio filters work perfectly.  Here is the link to the codepen demo.
https://codepen.io/Hayko/pen/EXKPvV
 Sorry for annoying design. I've just added portfolio part without any image and styles. After updating into Bootstrap 4 Portfolio columns were destroyed and each item shows in the row line while before  col-md-4  class worked. The second trouble is that filters don't work now. Can you help me to solve this trouble?

**Comment by Vestride** [comment]
Can you try the suggested fix for #103

**Comment by Vestride** [comment]
You're also not linking to Bootstrap 4's CSS in your codepen demo. It looks like this is also relevant for your situation: https://vestride.github.io/Shuffle/images

**Comment by Hayko1994** [comment]
Yes I know but in the original source it's  linked to bootstrap 4's  CSS and the problem is the same. Do you mean just change columns with flex-col and row with flex-row?  I did it like in the demo of #103 but the problem is the same.  Every item shows in the new line and filter buttons don't work again.

**Comment by Vestride** [comment]
> specify a `width` for each column

Do that in your CSS. You likely want a percentage width.

I can't really debug your demo because it's missing assets like bootstrap, jQuery, and images.

**Comment by Hayko1994** [comment]
I've integrated missing assets. Here is the link: 
[https://codepen.io/Hayko/pen/EXKPvV](url)

**Comment by Vestride** [comment]
You have 2 JavaScript errors. One of them is because [jQuery 3.0 removed the `load` method](https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed).

**Comment by Hayko1994** [comment]
I've fixed it but the result is the same :)

**Comment by Vestride** [comment]
It seems like you also upgraded from Shuffle v3 to v4 because you're still trying to use it as a jQuery plugin.

Please see the release notes for v4 https://github.com/Vestride/Shuffle/releases/tag/v4.0.0

**Comment by Hayko1994** [comment]
I am a bit confused. change shuffle into the filter. Also, change class names which destroyed all demo and I remove them. More than that cols again are starting from the new line. I really can't find the solution. Is there any demo example of a filterable portfolio with jquery code for Bootstrap 4? It's better for me to change existed example then spend so much time on figuring out the main problem with this script.

**Comment by Vestride** [comment]
I created a new demo for you which uses Bootstrap 4's grid and button components: https://codepen.io/Vestride/pen/weWbJQ
