### ISSUE TITLE
Give more animation options

### ISSUE THREAD

**Issue by jancbeck** [Vestride/Shuffle#155]
I have chosen Shuffle.js for a client project but the client doesn't like the transformation-heavy animations. 
It would be great if more control over the animations was possible such as "fade" or writing your own animation algorithm.

**Comment by Vestride** [comment]
I'm not sure what you're asking for.

You can already [customize the before and after styles for visible and hidden](https://vestride.github.io/Shuffle/#custom-styles) as well as the `ease` and `speed` [options](https://vestride.github.io/Shuffle/#options) to change the transition timing function and transition duration, respectively.
