### ISSUE TITLE
Initial sort functionality

### ISSUE THREAD

**Issue by ldemarinis** [Vestride/Shuffle#156]
I believe this may just be a case of me not completely understanding some of the more detailed concepts.  I am attempting to create and initialSort behavior that sorts the content from latest to oldest (obviously according to date).  I have this functionality working perfectly when using a drop-down sort feature.  

The data that is loaded into a razr case function gets loaded from the provider in order of what was created first to last.  There in lies my issue.  I cannot seem to figure out a way to, as mentioned, initially sort in reversed order.

Thanks for your time!

**Comment by Vestride** [comment]
Sounds like you want the `initialSort` option.
