### ISSUE TITLE
Shuffle v4 demo with ImagesLoad

### ISSUE THREAD

**Issue by mpetricek** [Vestride/Shuffle#159]
Hi,

I'm trying to solve problems with overlapping images with Shufflejs v4. Does anybody have functional demo anywhere?

Thank you

**Comment by Vestride** [comment]
I do not have a demo with `imagesLoaded`, but [reading their docs](https://imagesloaded.desandro.com/#jquery), you would simply need to initialize your shuffle instance inside the imagesloaded callback.

```js
$('#container').imagesLoaded(function () {
  var shuffleInstance = new Shuffle(containerElement);
});
```
