### ISSUE TITLE
Will this work with infinite scroll?

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#161]
If I were to integrate shuffle.js and [infinite scroll](https://github.com/metafizzy/infinite-scroll), would there be any conflict between them?

**Comment by Vestride** [comment]
Yes this will work with infinite scroll, no there should not be a conflict. You will need to listen for the [`append` event](https://infinite-scroll.com/events.html#append), then use the `add` method.

```js
infScroll.on('append', function(response, path, items) {
  shuffleInstance.add(Array.from(items));
});
```

**Comment by cameronroe** [comment]
Awesome, thanks!

**Comment by cameronroe** [comment]
@Vestride It turned out that the infinite scroll plugin doesn't work in my use case because it requires you to load specifically from a page and is very coupled. Can I ask what the array your plugin needs is?

For example, what is `items` in this case? An array of objects, dom nodes, strings, zebras, or flamingos? I need to know exactly what type of items are getting passed in.. I'm also confused how the items append. Are you saying we need to append the actual nodes and then, in addition, append the array to the shuffle instance? Why not just append it directly to the instance?

**Comment by Vestride** [comment]
https://vestride.github.io/Shuffle/#public-methods
https://infinite-scroll.com/events.html#append
