### ISSUE TITLE
Changing the height of the container?

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#162]
How would I change the height of the container? I look all through the docs and can't find anything. I have a box-shadow that's getting cut off from the overflow. I need to extend the height of the container by certain amount. I can just tweak it right?

**Comment by Vestride** [comment]
Add some `padding-bottom` to the container.

**Comment by cameronroe** [comment]
That doesn't work. The container is absolutely positioned based on the height of the Shuffle setting. I have a box-shadow on each element and it's getting cut off. Any other ideas?

**Comment by Vestride** [comment]
Override _setContainerSize? padding bottom has always worked for me

**Comment by cameronroe** [comment]
<img width="882" alt="screenshot 2017-07-25 22 08 50" src="https://user-images.githubusercontent.com/1614348/28601374-db066948-7185-11e7-9f12-efa0ee2060ce.png">

**Comment by cameronroe** [comment]
The padding doesn't add space between the bottom of the inner elements because they are absolutely positioned.
 
<img width="365" alt="screenshot 2017-07-25 22 09 14" src="https://user-images.githubusercontent.com/1614348/28601384-e7ebae0c-7185-11e7-893e-12a8b92b3d34.png">

**Comment by cameronroe** [comment]
The overflow cuts off the shadow. So the height must be greater from the js.

**Comment by cameronroe** [comment]
@Vestride How would I override `_setContainer`?

**Comment by cameronroe** [comment]
Okay, I've updated the code to:

```
Shuffle.prototype._setContainerSize = function () {
    this.element.style.height = this._getContainerSize() + 20 + 'px';
}
```

That appears to fix the issue. Thanks.
