### ISSUE TITLE
Overlapping tiles when changing figure size

### ISSUE THREAD

**Issue by ldemarinis** [Vestride/Shuffle#164]
I have a click event that expands the figure elements that changes the height of the object.  However, it seems when you change the size of a grid element on the fly the grid does not update and it results in an overlapping of images, divs, etc.

Is there anyway to re-render the grid when  this occurs, or at that, whenever I may need to do so... without reloading the whole page?

Thanks a bunch!

**Comment by ldemarinis** [comment]
Update:  I overlooked the documentation that has the update and layout methods.  I suppose I am confused as to where to call those... BTW, the attached is how I am initiating the shuffle instance.
![shuffle](https://user-images.githubusercontent.com/17166506/28576246-673af344-7121-11e7-9dbb-1a43fe2c8537.png)

**Comment by Vestride** [comment]
Try calling `this.shuffle.layout()` after you expand the size of your element(s).

**Comment by ldemarinis** [comment]
Thank you!  I worked this out a bit earlier, but either way, thank you for your time.
