### ISSUE TITLE
shuffleInstance.on undefined

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#165]
### What is actually happening?

<img width="1440" alt="screenshot 2017-07-31 22 11 50" src="https://user-images.githubusercontent.com/1614348/28806332-5c1ae2c8-763d-11e7-9e51-1f69fa3b2023.png">

**Comment by cameronroe** [comment]
Does the function not exist from the example?

```
shuffleInstance.on(Shuffle.EventType.LAYOUT, function () {
  console.log('Things finished moving!');
});
```

**Comment by Vestride** [comment]
Which version of shuffle are you using?

**Comment by cameronroe** [comment]
I'm using https://unpkg.com/shufflejs@4

**Comment by Vestride** [comment]
v4 is not an event emitter, it uses CustomEvent on the main element. You will need to use shuffleInstance.element.addEventListener.

**Comment by cameronroe** [comment]
What's the latest version? Is it hosted on a CDN?

**Comment by Vestride** [comment]
https://github.com/Vestride/Shuffle/releases
