### ISSUE TITLE
Need help for adding new items?

### ISSUE THREAD

**Issue by beratgashi** [Vestride/Shuffle#171]
I need help to add new items to my wordpress theme, need to add items with shuffle when loaded with ajax in button click but when I use this - demo.shuffle.add(data); it says that Cannot read property 'add' of undefined can you help me to solve this issue please?

**Comment by beratgashi** [comment]
Actually I think I understand how it works now but I don't know how to create items that cames from wordpress ajax to append them then to show them with shuffle.js !

**Comment by Vestride** [comment]
I cannot help you without seeing any code.

You can look at the `_getHtmlMarkupToAdd` method in demo file for an idea of what you need to do: https://github.com/Vestride/Shuffle/blob/v5.0.0/docs/js/demos/adding-removing.js#L81-L94

**Comment by Vestride** [comment]
You can then see how `_getHtmlMarkupToAdd` is used in the `onPrependBoxes` method.

```js
// Prepend HTML string.
this.element.insertAdjacentHTML('afterbegin', markup);

// Get the first 5 children of the container (we are inserting 5 items).
// If you want to *append* items, you will need to modify this line.
var items = Array.prototype.slice.call(this.element.children, 0, 5);

// Notify the instance.
this.shuffle.add(items);
```

**Comment by beratgashi** [comment]
This is my code

$(document).ready(function($) {
    $('nav.load-more > button').click(function(e){
        e.preventDefault();

        var button = $(this),
            data = {
            'action': 'loadmore',
            'query': trosha_lmp.posts, // that's how we get params from wp_localize_script() function
            'page' : trosha_lmp.current_page,
            'search' : trosha_lmp.is_search,
            'post_type' : trosha_lmp.post_type
        };
 
        $.ajax({
            url : trosha_lmp.ajaxurl, // AJAX handler
            data : data,
            type : 'POST',
            beforeSend : function ( xhr ) {
                button.addClass('loading'); // Add loading class
            },
            success : function( data ){
                if( data ) { 
                    button.removeClass('loading'); // Remove loading class
                    $('.items').append(data); // Append new data
                    trosha_lmp.current_page++;
 
                    if ( trosha_lmp.current_page == trosha_lmp.max_page ) {
                        // if last page, remove the button
                        button.attr('disabled', 'disabled');
                        button.addClass('disabled');
                        button.removeClass('loading');
                        button.text('no more posts!');
                    }
                } else {
                    button.attr('disabled', 'disabled');
                    button.addClass('disabled');
                    button.removeClass('loading');
                    button.text('no more posts!');
                }
            }
        });
    });
});

I want to append data inside this code but shuffle append isn’t working inside success method !

**Comment by Vestride** [comment]
So I'm guessing `data` inside your success callback is a string of HTML? I would probably write the code like this:

```js
var $newItems = $(data);
$(".items").append($newItems);
shuffleInstance.add($newItems.get());
```

**Comment by beratgashi** [comment]
I tried this code but it goes on infinite loop and how can I hide before append the data comes in bootstrap method col-sm-* !

**Comment by beratgashi** [comment]
And this is my shuffle code:

`var Shuffle = window.Shuffle;

var Demo = function (element) {
  this.element = element;

  this.shuffle = new Shuffle(element, {
    itemSelector: '.js-item',
    sizer: element.querySelector('.my-sizer-element'),
  });

  this._activeFilters = [];

  this.addFilterButtons();

  this.mode = 'exclusive';
};

Demo.prototype.addFilterButtons = function () {
  var options = document.querySelector('.filter-options');

  if (!options) {
    return;
  }

  var filterButtons = Array.from(options.children);

  filterButtons.forEach(function (button) {
    button.addEventListener('click', this._handleFilterClick.bind(this), false);
  }, this);
};

Demo.prototype._handleFilterClick = function (evt) {
  var btn = evt.currentTarget;
  var isActive = btn.classList.contains('active');
  var btnGroup = btn.getAttribute('data-group');

  // You don't need _both_ of these modes. This is only for the demo.

  // For this custom 'additive' mode in the demo, clicking on filter buttons
  // doesn't remove any other filters.
  if (this.mode === 'additive') {
    // If this button is already active, remove it from the list of filters.
    if (isActive) {
      this._activeFilters.splice(this._activeFilters.indexOf(btnGroup));
    } else {
      this._activeFilters.push(btnGroup);
    }

    btn.classList.toggle('active');

    // Filter elements
    this.shuffle.filter(this._activeFilters);

  // 'exclusive' mode lets only one filter button be active at a time.
  } else {
    this._removeActiveClassFromChildren(btn.parentNode);

    var filterGroup;
    if (isActive) {
      btn.classList.remove('active');
      filterGroup = Shuffle.ALL_ITEMS;
    } else {
      btn.classList.add('active');
      filterGroup = btnGroup;
    }

    this.shuffle.filter(filterGroup);
  }
};

Demo.prototype._removeActiveClassFromChildren = function (parent) {
  var children = parent.children;
  for (var i = children.length - 1; i >= 0; i--) {
    children[i].classList.remove('active');
  }
};

/**
 * Create some DOM elements, append them to the shuffle container, then notify
 * shuffle about the new items. You could also insert the HTML as a string.
 */
Demo.prototype.onAppendBoxes = function () {
  var elements = this._getArrayOfElementsToAdd();

  elements.forEach(function (element) {
    this.shuffle.element.appendChild(element);
  }, this);

  // Tell shuffle elements have been appended.
  // It expects an array of elements as the parameter.
  this.shuffle.add(elements);
};

document.addEventListener('DOMContentLoaded', function () {
  window.demo = new Demo(document.getElementById('grid'));
});`

**Comment by Vestride** [comment]
You would be much better off creating your own code than copying the whole demo file. `shuffleInstance` from my comment above is `this.shuffle` in my demo code you posted. The instance is what is returned from `new Shuffle(...)`

You can use the [codepen template] as a starting point if you want to play around with it.

**Comment by beratgashi** [comment]
Can you tell me what code is better for me I need only filter options and append function ?

**Comment by Vestride** [comment]
This should be all you need to do if you have copied the complete demo code.

```js
// Inside your `succes: function (data)` callback.
var $newItems = $(data);
$(".items").append($newItems);
window.demo.shuffle.add($newItems.get());
```

There are many demos and examples on the documentation site. If you have further questions, please refer to them.

**Comment by beratgashi** [comment]
It keeps giving me this error: Cannot read property 'add' of undefined

**Comment by Vestride** [comment]
I created an ajax demo separate from the adding and removing demo. Hopefully that will help you understand what you need to do.

https://vestride.github.io/Shuffle/ajax

**Comment by beratgashi** [comment]
Thank you Vestride,

Can you add the filter option to this demo to because I need to initialize Shuffle on page load!

**Comment by beratgashi** [comment]
Finally I'm close to end this but it destroys my grid when new data appended

Screenshot: [](http://i.imgur.com/VtM8fcp.jpg)

**Comment by Vestride** [comment]
Are you certain that the array of new items you are adding to the shuffle instance does not contain any items already controlled by the shuffle instance?

**Comment by beratgashi** [comment]
Yes array contains only the 4 items from page 2 in wordpress and actually are only 7 posts and next page contains 3 posts only !

**Comment by beratgashi** [comment]
I used only this part because the getItemMarkup has .reduce and in console it says that .reduce is not a function please I need to fix this can you assist me in my code!

```
// Create and insert the markup.
var markup = data;
gridContainerElement.insertAdjacentHTML('beforeend', markup);

// Save the total number of new items returned from the API.
var itemsFromResponse = data.length;
// Get an array of elements that were just added to the grid above.
var allItemsInGrid = Array.from(gridContainerElement.children);
// Use negative beginning index to extract items from the end of the array.
var newItems = allItemsInGrid.slice(-itemsFromResponse);

// Notify the shuffle instance that new items were added.
window.troshaFilter.shuffle.add(newItems);
```
