### ISSUE TITLE
IE9 no container inline style

### ISSUE THREAD

**Issue by dkeulen** [Vestride/Shuffle#178]
Currently i am testing my html,css,js grid with shuffle js for the filtering.
It works everywhere, also in IE9 with the specified polyfills you provided in the explanation.

BUT in IE9, the item container ( new window.Shuffle(document.getElementById('modules')...)
does not get its inline Style with the container height that it should be according to the viewable items with its filter (i display 12 items, but the container stays full height, showing white space beneath the 12 visible items, instead of collapsing the container).

Now my question is, am i forgetting a polyfill, or is this simply not gone be working in IE9 (or something else, i am not getting console errors about this issue?).

### Shuffle version
latest grabbed from this repo, previous week. (using plain min.js file within index.html. Not using npm)

### Reproduction Link
< none sorry >

### Steps to reproduce
Using shuffleJs in IE9 with specified polyfills: "https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Set,Array.from,Object.assign,Array.prototype.find,Array.prototype.includes"

(i used default aswell, because without default it wont work in the first place in IE9).

### What is Expected?
item container to have inline style with height of the container etc.

### What is actually happening?
item container does not receive inline styling, setting the container height correctly for the showing items.

![container-whitespace](https://user-images.githubusercontent.com/782885/30803627-97939164-a1ea-11e7-87e8-5d5da974f5ca.png)

![container-no-inline-styling](https://user-images.githubusercontent.com/782885/30803640-aa85759e-a1ea-11e7-9ee8-e2ab822095ce.png)

**Comment by Vestride** [comment]
Is the height still missing when you click the refresh button in the developer tools?

![screenshot 2017-09-25 11 52 38](https://user-images.githubusercontent.com/963921/30828889-ffd66ec8-a1f3-11e7-9b49-55cfe5e858e8.png)

I have a codepen demo of Shuffle with the correct polyfills working in IE 9 here https://codepen.io/Vestride/pen/dvExbg

**Comment by dkeulen** [comment]
You are right, when refreshing the console itself, it shows inline style.
But still for some reason, the containers height is not correct. Its not full height (all items visible) but halfway its total items height-ish).

After some fiddling i found out that in IE9 some css was being ignored. That way the hidden items stil had padding, and so, this got calculated in for the container height...

I got the container showing the correct height in IE9> now.

**Comment by Vestride** [comment]
👍
