### ISSUE TITLE
Multiple groups.

### ISSUE THREAD

**Issue by hifall** [Vestride/Shuffle#182]
I'd like to use Shuffle to manage multiple groups of items. Say I have 3 groups A, B, And C, and each group has some items in it. I'd like to divide the UI into 3 separate rows, with each row for each of the group. Each group's items stay inside the row when filtered/searched. Somewhat like the System Preferences UI in Mac OS X.

Is this possible with Shuffle?

Thanks!

**Comment by Vestride** [comment]
You would need to use multiple instances of Shuffle to accomplish that.
