### ISSUE TITLE
Triggering correct layout with image grid loaded dynamically from an API

### ISSUE THREAD

**Issue by jamesinealing** [Vestride/Shuffle#185]
### Reproduction Link
https://jsfiddle.net/qu1nbd2p/

### What is Expected?
5 columns of evenly spaced images

### What is actually happening?
On first load with a clear cache the images appear but overlapping. Resizing the window triggers the layout to refresh to correctly spaced images. Typically reloading (or hitting Play in the jsfiddle) without clearing the cache also does this, but a force refresh reverts to the overlapping 

### Things tried
I have tried shuffleInstance.update() which at least shifted from one column to five, but the vertical overlapping persists - see https://jsfiddle.net/qu1nbd2p/1/
I have used a .sizer element but I confess I'm not exactly sure from the docs how this works
I suspect it is because I am loading the images dynamically rather than any hard coded in the html, but just need to know what I can trigger to force the correct layout

**Comment by Vestride** [comment]
A couple things that will help you:

* The **sizer** element is supposed to be **inside the shuffle container** as a sibling to your items. Doing this fixed your demo. Shuffle will then use that element to determine the size of the grid columns and gutters, so you should treat it just like you would a regular item. It looks like you're using bootstrap, so check out the [flexbox grid](https://vestride.github.io/Shuffle/flexbox-grid) demo for a reference.
* If you know the exact dimensions or the ratio of your images ahead of time, you won't have to worry about them ever overlapping if you follow the suggestions in the [images demo](https://vestride.github.io/Shuffle/images).
* `update()` is the correct method to use when the column and gutters need to be recalculated as [described in the public methods](https://vestride.github.io/Shuffle/#public-methods). You shouldn't need to use this after using `add()` though.
