### ISSUE TITLE
Fade-In-Animation

### ISSUE THREAD

**Issue by PaperCoder** [Vestride/Shuffle#190]
I've got a question about an old code pen by you: https://codepen.io/Vestride/pen/xevIG

When adding new boxes in this pen, the elements fade in successively. I think this happens because the elements will be added one by one. I do want this behaviour for a regular new Shuffler project where I initiate the instance the standard way:

```
var shuffleInstance = new Shuffle(element, {
  itemSelector: '.picture-item',
  sizer: sizer // could also be a selector: '.my-sizer-element'
});
```
So the single boxes should fade in successively and not at the same time. Can you give me a hint how this would be possible?

**Comment by Vestride** [comment]
This option has been removed, but you could get something close by using a loop and `setTimeout` with `add()`

**Comment by PaperCoder** [comment]
I've just implemented it in in your suggested way. The tiles are now fade in successively. But the effect is different to the old code pen. Now, the tiles are "coming" from the left top position of the element. But I want them to fade in like in the pen, but I don't find the definition for that in the pen.

**Comment by Vestride** [comment]
Which version of Shuffle are you using?

**Comment by PaperCoder** [comment]
4.2.0

**Comment by Vestride** [comment]
Yes

**Comment by PaperCoder** [comment]
You're the men! Now I'm having my desired animation. Thx for your help!
