### ISSUE TITLE
Filtering by dynamic data attribute

### ISSUE THREAD

**Issue by b0gd4n** [Vestride/Shuffle#195]
I have a list of items each with a data attribute that changes depending on what filters you have selected.
I want to sort the list by that data attribute.

This is what the `_handleSortChange` function looks like:
`function sortByIndex(element) {
    return element.getAttribute('data-weightedindex');
  }
  const options = {
    reverse: true,
    by: sortByIndex
  };
  this.shuffle.sort(options);`

And the `data-weightedindex` gets updated depending on filters.
The problem is that the order of the sort is completely random and does to reflect the numbers present in `data-weightedindex`.

**Comment by Vestride** [comment]
What did you do to resolve this?

**Comment by b0gd4n** [comment]
@Vestride sorry - it turned out I was doing something weird with the data. It's working as expected. Thank you.
