### ISSUE TITLE
Sorting by second parameter

### ISSUE THREAD

**Issue by b0gd4n** [Vestride/Shuffle#197]
I have a list of items being sorted by a `weightedIndex` attribute. I want to handle the case where some of the items have the same `weightedIndex` and sort those ones by the `name` attribute (alphabetically). Is there way of doing this?

**Comment by Vestride** [comment]
No, there is not a way to do this currently.

You could predetermine the sort order with your own custom js, then use that order for your shuffle instance.

Say you want to sort by name, then age (asc) for some people.

```js
[
  { name: 'Zach', age: 32 },
  { name: 'Adam', age: 18 },
  { name: 'Adam', age: 15 },
]
```

Sort that by name, the by age so you end up with this:

```js
[
  { name: 'Adam', age: 15 },
  { name: 'Adam', age: 18 },
  { name: 'Zach', age: 32 },
]
```

Then, in your custom sort function, use that new order:

```js
shuffleInstance.sort({
  by: function (element) {
    return getOrderFromSortedItems(element);
  },
});
```

**Comment by Vestride** [comment]
Custom compare method added in `v5.1.0`
