### ISSUE TITLE
Assign more than one category to each item

### ISSUE THREAD

**Issue by BlueberryPuppyKisses** [Vestride/Shuffle#199]
Is there a way to assign more than one category to each item?

I have a working Isotope pen example here:
https://codepen.io/winteriscoming/pen/eyGQEN
in which one item has more than one category, for example: `data-category="1 2 all"` or `data-category="2 3 all"`

I was following this https://vestride.github.io/Shuffle/compound-filters example, but when adding more shapes or colours in `data-shape="square circle" data-color="red"` it doesn't work.

**Comment by BlueberryPuppyKisses** [comment]
Never mind, it's in https://vestride.github.io/Shuffle/#filters
Have learn to read, closed

**Comment by Vestride** [comment]
If you're using the default `data-groups` attribute to handle filtering, all you need to do is add another item to the array:

```html
<figure class="col-4@sm picture-item" data-groups='["nature","city"]'>…</figure>
```
