### ISSUE TITLE
Multiple shuffle on the same page

### ISSUE THREAD

**Issue by mderanty** [Vestride/Shuffle#202]
Hi,
I would like to know if it is possible to have two shuffle in the same page?

Cordially

**Comment by Vestride** [comment]
Yes.

**Comment by mderanty** [comment]
Can you explain to me how it works?
I have this script to initialize:
`if($('#portfolio').length)
	{
		var Shuffle = window.Shuffle;
		var element = $('#portfolio #galerie');

		var shuffleInstance = new Shuffle(element, {
			itemSelector: '.realisation',
			sizer: '.realisation',
			speed: 500,
		});
	}`

**Comment by Vestride** [comment]
Explain how what works?

**Comment by mderanty** [comment]
I need to display 3 filterable galleries on the same page.
And this script does not allow me to display the 3 but only one

**Comment by Vestride** [comment]
You would need to create 3 instances of shuffle.

```js
var Shuffle = window.Shuffle;

$('#portfolio #galerie').each(function (i, element) {
  var shuffleInstance = new Shuffle(element, {
    itemSelector: '.realisation',
    sizer: '.realisation',
    speed: 500,
  });
});
```
