### ISSUE TITLE
Keeping randomized order

### ISSUE THREAD

**Issue by creative-resort** [Vestride/Shuffle#204]
Currently, after applying a random sort order,
**on resize** the order is randomized **again**.

If I reset the sort using an empty sort option object, the order is not retained but reverted to DOM order.
If I disable shuffle, it doesn't respond to layout changes any more.

Is there a way to keep the order achieved with the initial random sort until it is explicitly sorted again,
while retaining responsive capability?

Thank you!

**Comment by Vestride** [comment]
Your best option is probably to create a random sort order yourself, save that order, and use it instead of the builtin randomizer.
