### ISSUE TITLE
New option for the "Sort" drop down.

### ISSUE THREAD

**Issue by darienmark2** [Vestride/Shuffle#208]
HI there - I'm using this great demo as an example: http://interactivejoe.com/book-viewer/  
For the drop-down "Sort By" list, how can I add whatever I want to that list? I would like to further sort from the filtered results.
So how can I add 'author' and 'year' as two more options?

I  already attempted troubleshooting by following "data-title" in the javascript -  but nothing happened. Can you help?

**Comment by Vestride** [comment]
https://vestride.github.io/Shuffle/#sorting
