### ISSUE TITLE
Different margin-top for each column

### ISSUE THREAD

**Issue by newkind** [Vestride/Shuffle#209]
Hi,

I was wondering if it's possible to have different margin-top for each column, so that each column starts at slightly different top position?

Thanks!

**Comment by Vestride** [comment]
Yes. Did you have difficulty doing that?

**Comment by newkind** [comment]
Yes, I wasn't actually able to do that. Can you please give me any hints about that?

**Comment by Vestride** [comment]
Without more information, there's no much I can recommend. `margin-top` on the item _should_ be working.

**Comment by newkind** [comment]
Sure, that's understandable. So I'm using your awesome shuffle.js script combined with Masonry from DeSandro and my goal is to have 4 columns of images/cards where each column has different margin at the top, so that each column (and not separate items) has different top position ie. column 1 has margin-top of 70px and column 2 has margin-top of 30px.

The issue is that I need this to be consistent with filtering of shuffle.js so that the margin-tops will be kept for filtered items. Because of that I can't target them by CSS (ie. using nth-child) as they are constantly getting shuffeled and change their positions in DOM.

**Comment by Vestride** [comment]
2 things come to mind:

1. Using Shuffle *and* Masonry for the same grid of items can cause conflicts. Shuffle uses a Masonry-like layout system, so you shouldn't need to use both at the same time for the same content.
2. Determining which elements are in which column and which ones are at the top could be quite difficult. You might be able to "fake" it by adding a couple `opacity: 0` elements such that they're always placed at the top of the container (custom sorting maybe?).

**Comment by newkind** [comment]
Thank you for your hints, I think that for the starters I'll play with the invisible elements. I'm going to close that ticket to not bother you with it anymore. One more time thank you.
