### ISSUE TITLE
Filtering does not work in IE 11

### ISSUE THREAD

**Issue by negarjf** [Vestride/Shuffle#210]
### Shuffle version
v5.0.3

### Reproduction Link

https://codepen.io/negarjf/pen/RxoQqb

### Steps to reproduce
I simply initiate the plugin and enabled "Filter by a group", following the instruction. Then I opened my page with IE 11.

### What is Expected?
Images should be filtered by clicking on top buttons.

### What is actually happening?
In Internet Explorer 11 filtering does not work. It seem that "includes" method of ES6 Javascript is not supported by IE according to MDN Web Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
Even babeljs and polyfill does not help.
I myself added a function to plugin for checking the browser and used "indexOf" instead of "includes" when IE 11 is detected. And it solved the problem as you can see in this codepen:
https://codepen.io/negarjf/pen/xpRWKM

I'm not sure if my solution is the best for this problem, so I've decided reporting it.

**Comment by Vestride** [comment]
Thanks for the well-written issue!

You need to add the polyfill yourself https://vestride.github.io/Shuffle/#polyfills
