### ISSUE TITLE
Portfolio items sometimes collapse and stack on top of each other....

### ISSUE THREAD

**Issue by pcross1986** [Vestride/Shuffle#212]
Version 3.3.1

Sometimes when the page loads, my portfolio items look collapsed and stacked upon each other.

![portfolio-shuffle-js-problems](https://user-images.githubusercontent.com/16227415/37237073-741154a8-23d4-11e8-92be-7a0ac278ccff.jpg)

Any idea why? It's weird because it only happens sometimes.

Here is how it should always load...
![portfolio-shuffle-js-corrected](https://user-images.githubusercontent.com/16227415/37237108-0d4f2898-23d5-11e8-8baa-70e7921561a8.jpg)

I can remove this link when issue is closed. Thanks.

**Comment by Vestride** [comment]
https://vestride.github.io/Shuffle/images

**Comment by pcross1986** [comment]
@Vestride Thank you greatly.
