### ISSUE TITLE
Wrong spelling of delimeter

### ISSUE THREAD

**Issue by abhisekp** [Vestride/Shuffle#215]
### Shuffle version
v5.1.1

### Steps to reproduce
The spelling of `delimeter` in the option should be `delimiter` instead.  

### What is Expected?
Spell Check: `delimiter`  
For backward compatibility, also accept `delimeter` along with `delimiter` (alias)

### What is actually happening?
Developers are going crazy due to unnatural spelling :smiley_cat:  
Sometimes, developers type the correct spelling and nothing works showing a JSON parse error.

**Comment by Vestride** [comment]
Thanks! 😬

**Comment by Vestride** [comment]
Published in 5.1.2
