### ISSUE TITLE
Don't hide non-matches; add style instead?

### ISSUE THREAD

**Issue by creativearc** [Vestride/Shuffle#222]
We have a use case of showing a familiar Shuffle grid of square tiles. Sorting and filtering are doing what we need, except for one thing:

The client wants the tiles to always appear. Instead of hiding them, we are going to dynamically apply a CSS style. (Imagine the non-matches dimming instead of hiding)

For example, if the tiles were varieties of Soda, and the filter choice was "Diet," we don't want Diet soda tiles to disappear. We just want to "dim" them with CSS.

Note: We do want to keep the standard re-ordering function so the tiles remain in the proper sort order.

**Comment by Vestride** [comment]
I think you might be better off implementing that on your own.

"hidden" items are completely ignored when Shuffle goes to find locations for the visible items. So even though you can customize the styles of the hidden items via `Shuffle.ShuffleItem.HIDDEN` and `Shuffle.ShuffleItem.Scale.HIDDEN`, the visible items will still be on top of them. You could find all the hidden items each time with `shuffleInstance.items.filter(item => !item.isVisible)`
