### ISSUE TITLE
Shuffle Button filters after ajax call demo?

### ISSUE THREAD

**Issue by alexisdrakopoulos** [Vestride/Shuffle#227]
I'm quite new to JS so I'm struggling with this. I can use ajax to import a JSON with all the info needed to generate a grid. However after that I can't filter it. 

If I type the HTML manually rather than generated via ajax I can easily filter it with buttons like in demo, but with the generated ones don't filter.

They just disappear no matter what button you click. Any idea what I could be missing?

**Comment by Vestride** [comment]
Hopefully you’ve solved this.

No code samples or demo, closing.
