### ISSUE TITLE
How to Display Message on Compound Filters When No Item Available

### ISSUE THREAD

**Issue by Behseini** [Vestride/Shuffle#235]
Hi,
Thanks for this but can you please let me know how we can export a "No Item Found" Message while using the Compound Filters and there is no item available in the

For Example if you select "**Red**" and "**Triangle**", the output is empty

![shuffle](https://user-images.githubusercontent.com/4685676/40857820-2752019a-6591-11e8-8bf5-acfd04b6f583.png)

where can we update the code to put no element with this filters available?

**Comment by Vestride** [comment]
There isn't anything built-in to Shuffle to do this, but it's pretty simple. You can listen for the LAYOUT event, then check if there are visible items.

```js
shuffleInstance.on(Shuffle.EventType.LAYOUT, function (data) {
  if (data.shuffle.visibleItems === 0) {
    // Show message.
  } else {
    // Hide message.
  }
});
```
