### ISSUE TITLE
Has anyone made it work with Bulma?

### ISSUE THREAD

**Issue by kilinkis** [Vestride/Shuffle#241]
hello!

I've been struggling with the grid and Bulma (https://bulma.io/documentation/columns/basics/).

Bulma, like BS4, is also flexbox based, so it also has the broken grid.
I tried this fix: https://vestride.github.io/Shuffle/flexbox-grid
and also this one: http://jsbin.com/logeyatiso/edit?html,css,js,output

neither worked.

So, real quick:
.columns is the Bulma equivalent for .row in Bootstrap.
.column is the immediate child of .columns.

.columns is flexbox.
I added a fixed width to each .column, as explained in the demos, but had no luck :(

I'll try to provide a fiddle or link ASAP, since my code in localhost for now.

**Comment by kilinkis** [comment]
@Vestride here is my grid: http://90d487d6.ngrok.io

do you see anything weird? is the div below the filters

thanks!

**Comment by Vestride** [comment]
Adding `column is-one-quarter` to your `my-sizer-element` fixed it for me.

The issue was that you're using the sizer to tell Shuffle the size of each column, but weren't setting a width on it, so it assumed the full width of the grid, making each item go to its own line.

**Comment by kilinkis** [comment]
God bless you sir!
thank you very much!
