### ISSUE TITLE
"ReferenceError: document is not defined" during build for SSR

### ISSUE THREAD

**Issue by srikanthbandaru** [Vestride/Shuffle#247]
Hello, 

Thank you for a great library. 
I am working on an SSR application and during the build, I am getting this error. 

![image](https://user-images.githubusercontent.com/8809165/44309980-8ebc6a00-a394-11e8-88f8-7d31bdd59566.png)

Is there a work around for this?

**Comment by Vestride** [comment]
Unfortunately I don’t think there is a workaround for Shuffle the way it’s
structured right now.

**Comment by Vestride** [comment]
Fixed in `5.2.0`. Let me know if you run into any further issues!

**Comment by srikanthbandaru** [comment]
That fixed the issue.
Thank you!!
