### ISSUE TITLE
Figures unload when out of the screen or hidden by sort

### ISSUE THREAD

**Issue by timotheeficat** [Vestride/Shuffle#257]
### Configuration
Shuffle.js version 5.2.0
Google Chrome Version 69.0.3497.100 (64bits)
Windows 7

### Steps to reproduce
I used the template at http://codepen.io/pen?template=qrjOpX and created 28 figures of the same sizes.

### What is actually happening?
When scrolling away from figures or when figures are hidden by a sort, the blocks are unloaded. Then when scrolling back to them or sort to any blocks, they have to reload which take too long and let an empty space until they are reloaded.

### What is Expected?
Figures should be always displayed and not unloaded to avoid the reload time after they are shown again.

### A question
Is Shuffle.js explicitly unloading figures when hidden or out of the screen or is this done by the web browser?

**Comment by timotheeficat** [comment]
So it seems to be a browser issue. I can't figure out why every blocks are unloading when they are out of the screen. It could be because of my computer running out of memory. But when I inspect the performance of the website it looks like it is using only 16M bytes or ram.

**Comment by Vestride** [comment]
You could also try disabling transforms by setting useTransforms to false.
That could remove some memory usage.

**Comment by timotheeficat** [comment]
I finally got it.
My images were too big. Because of this, my computer ran out of memory and my browser unloaded things on my website to save memory.
I'm not sure that it's a memory issue but when I resized my images it works well.
Thanks for your help!
