### ISSUE TITLE
Added object is not iterable in IE11

### ISSUE THREAD

**Issue by AndZyk** [Vestride/Shuffle#259]
### Shuffle version

5.2.0

### Steps to reproduce

First of all thank you for this plugin.

I doubt that this is a issue with Shuffle, but I would appreciate some help.

I have made a grid with Shuffle and want to add a object containing multiple HTML objects to this grid. I get this object with a jQuery Ajax request and following the demo for [adding and removing items](https://vestride.github.io/Shuffle/adding-removing), I first append the new HTML objects to the grid and then call `this.grid.shuffle.add(object)`. This works fine in every modern browser except in IE11 where I get the error:

>  TypeError(iterable + ' is not iterable!')

As mentioned in the section [dependencies](https://vestride.github.io/Shuffle/#polyfills) if have tried different polyfills:

- @babel/polyfill/dist/polyfill.js
- core-js/client/shim.js
- polyfill.io

But I always get the error, that my object is no iterable in IE11. I am not experienced in ES6, so I would appreciate some help how to get my object iterable in IE11.

Regards, Andreas

**Comment by Vestride** [comment]
is `object` an array? If you're using jQuery, you should be using the [`get()`](https://api.jquery.com/get/) method.

**Comment by AndZyk** [comment]
No, it was a object. Now I convert the object with [jQuery.makeArray](https://api.jquery.com/jQuery.makeArray/) and it works also in IE11.

Thank you very much for your help.
