### ISSUE TITLE
Can't get Shuffle.js to work in IE11 even with babel-polyfill

### ISSUE THREAD

**Issue by mgrandl** [Vestride/Shuffle#260]
I always get `SCRIPT438: Object doesn't support property or method 'forEach'` can somebody help please?

**Comment by mgrandl** [comment]
It clearly points towards the shuffle.js part of the bundle, so that's why I am opening the issue here.

**Comment by Vestride** [comment]
Can you see what line that is referencing? Are you passing real arrays (not
jQuery objects) to Shuffle’s methods?

**Comment by mgrandl** [comment]
real arrays not using jquery at all. I also made sure I am not using nodelists, but real arrays.

**Comment by mgrandl** [comment]
@Vestride nevermind, seems to be a problem in my build pipeline and unrelated to your plugin. Thank you very much for your work and sorry for the inconvenience!
