### ISSUE TITLE
[Demo] Sort items with a slider

### ISSUE THREAD

**Issue by anthonymasure** [Vestride/Shuffle#261]
Can you make a demo for sortering items with a slider? For example to use shuffle.js with the NoUISlider (https://refreshless.com/nouislider/). Can be helpful, for example, to sort items for a date range (min and max year).

**Comment by Vestride** [comment]
This seems like a very narrow use case to me.

You should be able to use [nouislider's events](https://refreshless.com/nouislider/events-callbacks/). You probably want to call `.sort()` on the shuffle instance on the `update` or `change` events from the range slider.
