### ISSUE TITLE
Support for lazy loading?

### ISSUE THREAD

**Issue by gidim** [Vestride/Shuffle#262]
Hi and thanks for a great library! 
In our use case we might have thousands of images and we're trying to reduce memory/network load on the browser. Is there a way to support lazy loading?

For example if there's no filters applied the library would only load/render the images that are in the viewport. Additional images would be loaded when the user scrolls and extends the viewport.

Thanks!

**Comment by Vestride** [comment]
Shuffle won't support this, but there are many libraries for lazy loading images. There's also a native [`lazyload`](https://calibreapp.com/blog/2018-08-16-native-lazy-load/) attribute coming in the future.

Here's a great guide on lazy loading images https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/
