### ISSUE TITLE
Sort in column direction possible?

### ISSUE THREAD

**Issue by dreg** [Vestride/Shuffle#264]
This is a long shot, but is it possible to have the sort order go from top to bottom in the columns instead of left to right? For example:

Normal alpha sort:

| .  A .   | .    B .   | .   C .    |
| .  D .   | .    E .   | .   F .    |

Alpha sort in columns (top to bottom, then wrap):

| .  A .   | .    C .   | .   E .    |
| .  B .   | .    D .   | .   F .    |

Thanks!

**Comment by Vestride** [comment]
Not in Shuffle. I think Isotope might have a column-based layout mode.
