### ISSUE TITLE
Is there a way to add prefilled text to the search box?

### ISSUE THREAD

**Issue by ssgfanboy** [Vestride/Shuffle#267]
Hello, I am learning HTML/CSS/JS and I would like to add text to the search box but I am unsure how I would go about doing this. Also is there a way of changing the colors in the sort menu and text color in the image gallery? Thank you for making this image gallery.

**Comment by Vestride** [comment]
For text in a search box, use the [`placeholder`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#The_placeholder_attribute) attribute which. If you want the text to be "real", use the `value` attribute.

MDN is a great resource and you can find many of the answers to your more general questions on stackoverflow.com.

Fair warning, Shuffle is a fairly complex library for a beginner to be learning with/from.
