### ISSUE TITLE
How to Access Sorted Table Order?

### ISSUE THREAD

**Issue by d8ahazard** [Vestride/Shuffle#268]
Hi there,

Not sure if this is a feature request, or maybe just something I'm unsure of how to do.

I'm trying to use your plugin in conjunction with "lightgallery".

Lightgallery likes to query the DOM to get the order that it builds it's media in.

So, if I sort my media in any way, it's not displayed in the correct order in the gallery...

Not a big issue for most directories, but in a few, it would be nice to access the data list of ordered elements. I looked at the listener/data for eventtype.LAYOUT, but can only seem to find the list in it's original order.

If I could get the sorted list of data, I could then manually move the elements around in the dom as needed.

**Comment by fearlex** [comment]
@d8ahazard Were you ever able to get the sorted list data ?

**Comment by Vestride** [comment]
I have not added this. If I were to add this property, this is where it would be updated with `items`.

https://github.com/Vestride/Shuffle/blob/8d8328fe0ace92924e5e06f27eaa8f3dee655764/src/shuffle.js#L816

**Comment by Vestride** [comment]
Added with #351. Released in v5.4.1.

Use the new `sortedItems` property to get the sorted items.
