### ISSUE TITLE
Question - Limit visible items?

### ISSUE THREAD

**Issue by kilinkis** [Vestride/Shuffle#270]
### Question or feature request

First, great library! works great :)
but I was wondering:

Is there anyway to limit how many items are displayed?
Let's say I have list of 20 items, but I want to display a maximum of 10.
The idea is to show 10 items tops, but the filters to work on the whole 20 items, that's why we load 20 initially.

I tried using some CSS selectors like `.shuffle-item--visible:nth-child(n+9)` but didn't work, as when you start adding filters, only items of the initial shown group are being displayed.

Thanks in advance

**Comment by Vestride** [comment]
I don't think there's an easy way to do this. You'll have to use custom filters and a counter to hide any item that's past your visible counter.

**Comment by Nightshadelink** [comment]
Is this still up to date? The feature or at least a custom filter that can do just that would be awesome!
