### ISSUE TITLE
Question: Getting Pictures from MySQL, using PHP, Infinity Scroll and Shuffle.js

### ISSUE THREAD

**Issue by neoone256** [Vestride/Shuffle#273]
### What I need to do:
Hello! I have a php website and I want to use Shuffle.js, with Infinite Scroll since the gallery will have lots of pictures and I am worried about performance. I already have the Shuffle working because I got it from the codepen template.

### My Questions:

- Do you know if it is possible to use this -> "mydomain.com/gallery.php?p=1" to use the Infinite Scroll to call pages from MySQL? If so, do you have any reference I can look at?

- Do you know of any Shuffle.js + Infinite Scroll tutorial or demo? I am really having a bad time doing this.

Kind regards

**Comment by neoone256** [comment]
Hello! If someone has an answer for my question, please help me.

**Comment by Vestride** [comment]
I don't have enough experience with MySQL to give recommendations.

I haven't used Shuffle with Infinite Scroll, but I don't see any reason it wouldn't work. There is a shuffle demo for animating items as they come into the viewport: https://github.com/Vestride/Shuffle/blob/7ab9d95dc8426c2e705313b660c7258e44d172f2/docs/js/demos/animate-in.js
