### ISSUE TITLE
Elements in row changes due to Window Scroll

### ISSUE THREAD

**Issue by dangrima90** [Vestride/Shuffle#280]
I have an issue where a three column list is being changed to a two column list after filtering the items. My guess is that the issue is being caused due to the window scroll after a window resize.

**Before filtering:**
![image](https://user-images.githubusercontent.com/36479149/55969692-89db5c00-5c7e-11e9-8337-dfec96399b08.png)

**After Filtering;**
![image](https://user-images.githubusercontent.com/36479149/55969763-a5466700-5c7e-11e9-919f-98a5267a4b5d.png)

From what I can see on load the width of the window scroll is not being taken into consideration, then after resizing the window items move slightly to adjust to the new width.

**Items on window load:**
![image](https://user-images.githubusercontent.com/36479149/55970121-446b5e80-5c7f-11e9-95c5-68ca0aa96841.png)

Here you can notice that the items appear to be "underneath" the window scroll.

**Items after window resize:**
![image](https://user-images.githubusercontent.com/36479149/55970184-5ea53c80-5c7f-11e9-80e0-81bad9ca0188.png)

Item positions have been adjusted to cater for the window scroll.

When filtering after resizing the window the issue shown above occurs when the window goes from having a scroll, to not having a scroll, and then again going back to having a scroll.

I will explain how to reproduce this below.

### Shuffle version
**Shuffle Version**: 5.2.1

### Reproduction Link

**Code:** https://stackblitz.com/edit/shuffle-js-window-scroll
**Demo:** https://shuffle-js-window-scroll.stackblitz.io/

### Steps to reproduce

1. Go to https://shuffle-js-window-scroll.stackblitz.io/
2. Make sure window is not full screen, so that you can resize the window
3. Resize window slightly so that items adjust to the window width including the scroll
4. Use the buttons on top to filter the items

If the window is set that when the items are filtered there isn't a scroll you should be able to reproduce the issue.

Also when this issue occurs clicking the filter buttons multiple times, amount of elements in row changes with every click.

### What is Expected?
I expect that the window scroll is taken into consideration on load and after items are filtered in case that the list of items causes a window scroll.

Sorry for the long post, hope it helps to reproduce the problem. Thanks in advance.

**Comment by Vestride** [comment]
I was only able to reproduce this one time, so I haven't really been able to debug it. I have a few suggestions on how you can debug further though:

1. Try setting `columnThreshold` to a higher value.
1. Remove the `gutterWidth` option and set inner padding on each of the items to create a gutter. Since you're using the `sizer` option, the gutters should be coming from the `margin-left` value of the sizer element.
1. The function which sets the number of columns is `_setColumns`. You can set a breakpoint in the debugger to see what's happening. You should be getting `12` columns, but in some cases you're likely getting `11`, which causes the layout to be wrong.

**Comment by dangrima90** [comment]
Thanks for your reply I will try your suggestions and debug a bit more. In the meantime I have updated the demo (https://shuffle-js-window-scroll.stackblitz.io/) to make it easier replicate the issue. I have added a filter which shows just one item.

With this new filter it's easier to go from having a scroll to not having a scroll.

To replicate you can have a look at this:

https://im.ezgif.com/tmp/ezgif-1-dd144f1ef8f1.gif

**Comment by dangrima90** [comment]
I have tested removing the `gutterWidth` and using the `columnThreshold` property as you suggested and it does seem to have done the trick.

**Code:** https://shuffle-js-window-scroll-v3.stackblitz.io
**Demo:** https://shuffle-js-window-scroll-v3.stackblitz.io/

I am now setting Shuffle using the following properties:

```
this.shuffleInstance = new Shuffle(this.shuffleContainer.nativeElement, {
        itemSelector: '.shuffle-item',
        sizer: this.shuffleSizer.nativeElement,
        columnThreshold: 1
});
```

What I'd like to understand is what does the `columnThreshold` property represent?

I'm asking because whilst testing I set a value of 100 and then a value of 1 which "from the outside" resulted in the same thing. Basically to the Shuffle library is there a difference between a `columnThreshold` of 1 and 100 for example?

Thanks again for your help.

**Comment by Vestride** [comment]
> Reading the width of elements isn't precise enough and can cause columns to jump between values.

https://github.com/Vestride/Shuffle/blob/5115fbd2400e5a8ed22997fbac407e3b551d511f/src/shuffle.js#L432-L437

It's a way to handle calculating how many columns there should be based on the column and gutter width. That `calculatedColumns` is then rounded down to the nearest number (`Math.floor`).

**Comment by dangrima90** [comment]
@Vestride Okay thanks a lot for your help and explanations :) have a good one!
