### ISSUE TITLE
Error TS2339: Property 'on' does not exist on type 'Shuffle'.

### ISSUE THREAD

**Issue by kmturley** [Vestride/Shuffle#294]
**Shuffle version**
v5.2.2

**Describe the bug**
When using Typescript to load ShuffleJS and listen to the layout event. Typescript complains the .on function does not exist. I believe because this function is inherited from the tiny-emitter library you use.

**Reproduction link**
Tried to replicate here, but Typescript not running properly in codepen: https://codepen.io/kmturley/pen/xxKrmZz

**To Reproduce**
1. Create a default demo using Typescript
2. Add the event:
```
myShuffle.on(Shuffle.EventType.LAYOUT, () => {
  console.log('on layout event!');
});
```
3. Run TypeScript compiler to see error

**Expected behavior**
It to compile correctly

**Desktop:**
 - OS: All
 - Browser: All 
 - Version: All

**Smartphone:**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
By adding the following code to index.d.ts it fixes the issue:

```
  /**
   * On shuffle event
   */
  on(eventType: Shuffle.EventType, func: Function): void;
```

**Comment by Vestride** [comment]
Thanks for reporting!

**Comment by kmturley** [comment]
Thanks for the quick turnaround 😀
