### ISSUE TITLE
Sorting options by asc, desc

### ISSUE THREAD

**Issue by buckyj** [Vestride/Shuffle#295]
It would be great to have an option for sorting ordering ascending and descending. I have data attribute price and would need both ways sorting option. Is it possible to modify the code to make this work?
Thank you!

**Comment by Vestride** [comment]
Use `reverse` or `compare` https://vestride.github.io/Shuffle/#sorting

**Comment by buckyj** [comment]
I have used this code snippet. Where can I define options reverse here? Thank you

shuffleInstance.sort(*options*{
  compare: function (a, b) {
    var ageA = parseInt(a.element.getAttribute('data-age'), 10);
    var ageB = parseInt(b.element.getAttribute('data-age'), 10);
    return ageA - ageB;
  },
});
