### ISSUE TITLE
Layout broken on Latest Chrome 80 Windows

### ISSUE THREAD

**Issue by auscaster** [Vestride/Shuffle#306]
**Shuffle version**
v 5.2.3

**Describe the bug**
The masonry layout breaks on Windows Chrome Version 80.0.3987.132 (Official Build) (64-bit). On Chrome Linux and other major browsers it still appears to be working as it should. This issue affects all the examples on the demo page: https://vestride.github.io/Shuffle/

**Reproduction link**
https://vestride.github.io/Shuffle/
https://artzine.com/gallery

**Screenshots**
![image](https://user-images.githubusercontent.com/100876/76276555-d6397c80-62d1-11ea-9e1b-28863761a540.png)
![image](https://user-images.githubusercontent.com/100876/76276574-e6515c00-62d1-11ea-8fad-94b075400629.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by auscaster** [comment]
This is unfortunately still an issue. I was hoping not to have to change libs but this one is a deal breaker.

**Comment by NicoVIII** [comment]
I can not reproduce that with Chrome or Firefox. The site works without problems for me.

**OS**: Windows
**Chrome**: Version 81.0.4044.138 (Offizieller Build) (32-Bit)
**Firefox**: 76.0 (32-Bit)

**Comment by Vestride** [comment]
I don't see this issue in browserstack. Closing.
