### ISSUE TITLE
Push Float Left Elements After Removing one From Shuffle Items

### ISSUE THREAD

**Issue by Behseini** [Vestride/Shuffle#309]
Can you please take a look at [This Demo](https://codepen.io/mona-martini/pen/jOPjGYo) and let me know why visible items are not floating left after removing on item from the list by request?

I have to remove some items from the list based on user request but after removing the item the item space left empty and the next existing item is not moving into removed item place. I test this and animation is happening only when shuffle is not applying( In Bootstrap).

Thanks

**Comment by Vestride** [comment]
Hi @Behseini, the codepen demo you linked is blank. Did you solve your issue?
