### ISSUE TITLE
Adding to Remove All By Group or All at Once Filters in Compound Filters

### ISSUE THREAD

**Issue by Behseini** [Vestride/Shuffle#310]
**[Demo](https://codepen.io/mona-martini/pen/ExVYmYr)**

Can you please take a look at above demo and let me know how I can add new event listener to the #cb-allcolors , #cb-allshapes, and #cb-all checkboxes to remove filters from the shuffle js?

What I would like to do is when user clicks on #cb-allcolors checkbox this will uncheck all checkboxes in the js-colors and refresh(re-load) the shuffle based on new changes.

Thanks

**Comment by Vestride** [comment]
To clear all filters, you can

```js
shuffleInstance.filter(Shuffle.ALL_ITEMS); // or .filter()
```

https://vestride.github.io/Shuffle/#filters
