### ISSUE TITLE
position not calculated right

### ISSUE THREAD

**Issue by ceehaupt** [Vestride/Shuffle#317]
**Shuffle version**
v5.2.3

**Describe the bug**
The position calculation went wrong! I added all the styles and a similar markup, but the third item isn't positioning at the right. When i take the script off the third item floats on the far right.
I used the import function to call the script like this:

```js
import logging from "node-logging-js";
import jsb from "node-jsb";
import Shuffle from "shufflejs";
class Journal {
    constructor(element, options) {
        logging.applyLogging(this, "Journal");
        this.logDebug("options:", options);
        this.element = element;
        this.masonry = this.element.querySelector(".js-grid");
        this.initialize();
    }
    initialize() {
        this.shuffleInstance = new Shuffle(this.masonry), {
            itemSelector: ".js-item",
            sizer: ".js-shuffle-sizer"
        }
    }
}
jsb.registerHandler("Journal", Journal);
export default Journal;
```

**Expected behavior**
I would like that the full width

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - newest Version
<img width="1439" alt="Bildschirmfoto 2020-07-23 um 21 58 23" src="https://user-images.githubusercontent.com/4174483/88333024-cb86fd80-cd2f-11ea-9ff2-31ffba1d8f98.png">

**Comment by Vestride** [comment]
can you provide a reduced test case?

**Comment by auscaster** [comment]
I has the same issue: https://github.com/Vestride/Shuffle/issues/306
