### ISSUE TITLE
compound filter with search does not work

### ISSUE THREAD

**Issue by alombia** [Vestride/Shuffle#324]
Ive been using the compound filter demo from your demo pages and it all works. However, when I try to add a search filter to it also, it does not work. It shows "Uncaught TypeError: Cannot read property 'textContent' of null". The code that causes the problem appears to be : var titleElement = element.querySelector('.picture-item__title');

**Shuffle version**
v

**Describe the bug**

**Reproduction link**
A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug. You can use this "Shuffle with Images" template on CodePen to get started: http://codepen.io/pen?template=qrjOpX

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oohohoo** [comment]
Hello :) I need help, please. i have similar problem. Everything works as expected except search. This codepen is fork from compound demo with search code added on line 215. Please help :) Thank you very much  https://codepen.io/fogseller/pen/JjWrgqe

**Comment by oohohoo** [comment]
@alombia Hey, hello :) did you ever solved this problem?

**Comment by Vestride** [comment]
@oohohoo you added the search methods, but then never called `addSearchFilter` anywhere. Adding that works.

**Comment by oohohoo** [comment]
@Vestride Hey mate, thank you 😀 but can you please tell me how to do it, what to put where? i'm just a beginner student :(  thank you very much

**Comment by Vestride** [comment]
<img width="1792" alt="Screen Shot 2021-05-29 at 10 43 47 AM" src="https://user-images.githubusercontent.com/963921/120079869-d060c000-c06a-11eb-9a97-c820ab1b0f4e.png">

**Comment by oohohoo** [comment]
YEAH! thats it it woooooorks thank you very very much! it works GREAT! yeah! 👯

**Comment by oohohoo** [comment]
last one, i promise :) how to search only already filtered items. for example if i filter 1 = megaboard and filter 2 = zagreb, and after that search for example "Bigboard". search  result shows Billboard and overrides filter 1 and 2. is there any simple way that they works together. thank you mate :)
