### ISSUE TITLE
Shuffle inside a modal/hidden block creates only one column

### ISSUE THREAD

**Issue by raghavendra89** [Vestride/Shuffle#331]
**Shuffle version**
5.2.3

**Describe the bug**
Shuffle inside a modal/hidden block creates only one column.

**Reproduction link**
https://jsfiddle.net/zhsq8gp4/

**To Reproduce**
1. Go to the above link
2. Click on `Add items and launch`

**Expected behavior**
A layout with multiple columns. In the above example there should be 4 columns.

**Screenshots**
This is actual image from my website:
![image](https://user-images.githubusercontent.com/8619262/104652609-5a714300-56df-11eb-8440-b1380f6182f7.png)

**Additional context**
In my case the content is in a hidden block. I tried calling the `.layout()` method after the Shuffle is initiated, but it did not work.

**Comment by laptopisasset** [comment]
Did u find any work around for this issue

**Comment by Vestride** [comment]
The sizer in the jsfiddle doesn't have any column classes on it. When shuffle attempts to measure it's size, it receives zero. Add the same grid classes as your items to the sizer and your issue will be fixed.
