### ISSUE TITLE
Ajax lazy load sort behaviour

### ISSUE THREAD

**Issue by raghavendra89** [Vestride/Shuffle#332]
**Is your feature request related to a problem? Please describe.**
I've implemented the shuffle with ajax and lazy load. I've a sorting filter, so the users can sort the items alphabetically. Now suppose sorting is enabled and the user is somewhere down the page and the items are lazy loaded, then the items are added at the random positions (based on the alphabetical order). 

The latest lazy loaded items may be added at the beginning, then the user has to scroll up to the beginning to see the new content. Then again they have scroll down to load the fresh items. So this is not a good user experience.

**Describe the solution you'd like**
I think it will be good if the lazy loaded items are added at the end until the user clicks on the filters. So need an option to disable sorting while adding new items.

**Is it possible to achieve this?**

**Comment by Vestride** [comment]
There is not a clean way to achieve this.

What you could do, which is a bit hacky, is this:

1. When a user requests that you sort the items, instead, update the DOM order of the items.
2. While lazy loading, append to the end of the shuffle container
3. Items now show up at the end, and are sorted.
