### ISSUE TITLE
Strict additive mode

### ISSUE THREAD

**Issue by pierrevano** [Vestride/Shuffle#333]
**Is your feature request related to a problem? Please describe.**
Currently additive mode = display the element if the element has at least one of the active filter (logical OR operator). 

**Describe the solution you'd like**
Add a STRICT additive mode = display the element only if the element has ALL the active filters (logical AND operator). 

**Describe alternatives you've considered**
None currently

**Additional context**
For music or movies filtering for instance.

**Comment by Vestride** [comment]
Hmm, is this the same as the [`FilterMode` option](https://vestride.github.io/Shuffle/docs/configuration#filtermode-shufflefiltermode)?
