### ISSUE TITLE
Callback when results from filter are empty

### ISSUE THREAD

**Issue by katsar0v** [Vestride/Shuffle#338]
Hello, I have a grid with filters, which work flawlessly, but when results are empty, I would like to show custom html content, is thiad doable with shuffle.js?

**Comment by Vestride** [comment]
There isn't a built-in way to do this.

You could listen for the layout event, and when there are no items visible, reveal you fallback content above it.

**Comment by katsar0v** [comment]
The layout event is fired before animation is ended, so it does not help unfortunately :(

**Comment by Vestride** [comment]
It shouldn’t be

https://github.com/Vestride/Shuffle/blob/e815e91009fe6d41366435600e27dcc7dcd0177c/src/shuffle.js#L779
