### ISSUE TITLE
Stop working - SiteNav.handleResize

### ISSUE THREAD

**Issue by Deight8** [Vestride/Shuffle#342]
**Shuffle version**
last

**Describe the bug**
After a few weeks, my filters stopped working and there was a problem with the site-nav.js file, please help and thynk you for time!

```
2site-nav.js:43 Uncaught TypeError: Cannot read property 'offsetHeight' of null
at SiteNav.handleResize (site-nav.js:43)
```

**Reproduction link**
https://teevee.fun/fre/

**To Reproduce**
Error is in index console.

**Desktop (please complete the following information):**
All

**Comment by Vestride** [comment]
Hi. the site navigation JavaScript for my demo site is not part of the Shuffle package and I won't be providing support for it.
