### ISSUE TITLE
Performance problems on iPhone - JavaScript crashes

### ISSUE THREAD

**Issue by flozzel** [Vestride/Shuffle#371]
I have a project with a larger number of items (~930).
When the application is used on iPhone and filtering or sorting is used, it first triggers a reload of the page and the next time an error page is displayed: A problem has repeatedly occurred on "Page Url".

The problem is probably caused by the many CSS-style changes of the items and their poor performance

I can provide a link to the project for testing purposes if desired.

**Comment by Vestride** [comment]
If you provide a reduced test case, I may be able to help.

**Comment by flozzel** [comment]
It is a little bit difficult for me to create a reduced test case, because I am using several own filters and a scrolling effect. 
I am not asking for you to debug my project, but I have already tried everything and it would be very kind if you maybe could take a quick look at it.

https://www.kd-onlinespende.de/geben.html
