### ISSUE TITLE
Already clicked sort input is not working on Firefox refresh

### ISSUE THREAD

**Issue by pierrevano** [Vestride/Shuffle#376]
**Shuffle version**
v5.4.1

**Describe the bug**
Clicking on an already clicked sort input after refreshing the Firefox page doesn't work

**To Reproduce**
1. Go to the ShuffleJS website : https://vestride.github.io/Shuffle/
2. Click on Title sort input : the sort action works the first time
3. Refresh the page with CMD+R or F5
4. Click on the **same** input
5. Nothing happens and the input can't be clicked

**Expected behavior**
1. The input should trigger the sort action like it does on Chrome

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser Firefox
 - Version 96

**Comment by Vestride** [comment]
Looks like this is [intentional behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1459865#c1) on Firefox's part. The workaround is to add `autocomplete="off"` attributes to every checkbox.

**Comment by Vestride** [comment]
Demos are fixed now.
