### ISSUE TITLE
Show all - missing

### ISSUE THREAD

**Issue by parken26** [Vestride/Shuffle#393]
I may be missing it, but I do not see any way to restore everything, after doing a filter and sort, except form refreshing the page - can this be added to the javascript, please?
Thank you!
Brgds Martin

**Comment by parken26** [comment]
It just came to me! By shear coincidence. To clear any filters applied, you just uncheck the filter - it is an on/off button! Brilliant solution, very nice but maybe not intuitive even though it should be. This is behaving just like any other button you may use everyday, in the car or the kitchen.

**Comment by Vestride** [comment]
See "Show all items" in the docs https://vestride.github.io/Shuffle/#filters
