### ISSUE TITLE
v3.0.0 cuts last element before moving it to the next row

### ISSUE THREAD

**Issue by luopio** [Vestride/Shuffle#46]
Everything works beautifully in 2.1.1. I'm testing by using the same layout, same JS code and just switching between release 3.0.0 and 2.1.1: 

  $('.properties-listing-container').shuffle({
      itemSelector: '.property-listing',
      columnWidth: 300,
      gutterWidth: 20
  });

Container is a div with article-elements inside. Article has fixed width of 300px. 

v2.1.1 works correctly:
![v2 1 1](https://cloud.githubusercontent.com/assets/69383/4697414/a9aef03a-5825-11e4-950c-aa1cf58483d2.png)

v3.0.0 won't update until around 1160px container width, which results in cutting the last element. Also note the behaviour on second line.
![v3 0 0](https://cloud.githubusercontent.com/assets/69383/4697413/a9ab725c-5825-11e4-8421-7400f35fd650.png)

Same thing happens in FF (33) and Chrome on Ubuntu 14.04. Also witnessed on Mac by other devs in my team.

**Comment by Vestride** [comment]
Released v3.1.0. There is now a new option `columnThreshold` and updated logic to retrieve non-integer widths of elements.
