### ISSUE TITLE
Shuffle sometimes forgets sort order when changing filters

### ISSUE THREAD

**Issue by Bilge** [Vestride/Shuffle#472]
**Shuffle version**
v6.1.0

**Describe the bug**
Shuffle sometimes _forgets_ sort order when changing filters.

**Reproduction link**
One day

**To Reproduce**
Try it here: https://club.steam250.com/tags#AJMAAQI

**Expected behavior**
Do not forget.

**Screenshots**
In this video, we see two button groups: sort buttons on the left and filter buttons on the right. The sort order is set to _frequency_, which is the number displayed inside each tag. The sort order is always reverse, i.e. highest frequency (largest number) to lowest. By playing around with the filters a bit, we can eventually coerce Shuffle into conveniently _forgetting_ it is supposed to sort in reverse frequency order.

![](https://github.com/Vestride/Shuffle/assets/470626/f731966d-cfce-4f7e-aafc-b22eba7404ed)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 108.0.1 (64-bit)

**Comment by Bilge** [comment]
Added not to clarify Shuffle only forgets the sort order when when the filter is set to the empty array (though not always).

**Comment by Bilge** [comment]
The sort buttons just call `sort({by})` and the filter buttons just call `filter(array)`. That is, we never pass `SortOptions` to `filter()`. Probably this issue could be worked around by keeping track of the current `SortOptions` in my implementation and repeating them in `filter()` calls, but it is supposed this should be handled by the library already.

**Comment by Bilge** [comment]
Even forcefully (re)setting the `SortOptions` when changing the filters **does not** fix the issue: when Shuffle decides it's going to ignore the sort options, it is absolutely adamant that it is going to ignore the sort options in this animation tick, whether or not we redeclare them or not. Moreover, it does not matter whether we redeclare the sort options before or after changing the filters.

Nevertheless, redeclaring the sort options manually some ticks later still works.

**Comment by Bilge** [comment]
I don't really feel like the original video was very clear, so I made a new one. Also the note about empty arrays is completely irrelevant.

![firefox_MTvPNhor4L](https://github.com/Vestride/Shuffle/assets/470626/f731966d-cfce-4f7e-aafc-b22eba7404ed)

In this clip we see the sort order is ignored the first time a filter group is added, but corrected when it is removed and re-added *or* when another filter is added.

**Comment by Bilge** [comment]
OK. But it is a bug in Shuffle.

**Comment by Vestride** [comment]
Cool.
