### ISSUE TITLE
Bug in official docs

### ISSUE THREAD

**Issue by jaroslaw-filipiak** [Vestride/Shuffle#492]
You have typo issue in getting started area in docs on this text : 

_"Alternatively, you can set the delimiter option to a comma (delimiter: ',') and the data-groups attribute will be split on that character."_

if you have classic output on item for example : 

` "data-groups='["nature","city"]'>"`

 its all good but if you want to change this output to comma separated for example to : 

`"data-groups="nature, city""`

you should set magic attribute and its not delimiter... its **delimeter**

`var shuffleInstance = new Shuffle(element, {
		itemSelector: 'li',
		delimeter: ','
});
`

so guys give me back my mental health xd

**Comment by Vestride** [comment]
Can you link to the page which has the typo? The only place `"delimeter"` is now mentioned is the changelog: https://github.com/search?q=repo%3AVestride%2FShuffle%20delimeter&type=code

**Comment by jaroslaw-filipiak** [comment]
https://vestride.github.io/Shuffle/docs/getting-started

**Comment by Vestride** [comment]
I'm sorry, I'm really not understanding what the issue is. What needs to be updated here?

https://github.com/Vestride/Shuffle/blob/7f695c09c0dfe6312770b5475452fd6f153ea38f/apps/website/docs/getting-started.md?plain=1#L30

**Comment by jaroslaw-filipiak** [comment]
change 'delimiter' to 'delimeter' in line 30 !

**Comment by Vestride** [comment]
Delimiter is the correct spelling for v6. Previously, both were allowed.

**Comment by jaroslaw-filipiak** [comment]
Yea sure you have 2 options "delimeter" and "delimiter" - i agree with this.
but if you have in data-group output not valid json for example : data-groups="nature, city" not data-groups='["nature","city"]' 
you must set delimeter option to settings not delimiter

pls read my first comment and look at the documentation and dont waste my time again

**Comment by jaroslaw-filipiak** [comment]
Yea sure you have 2 options "delimeter" and "delimiter" - i agree with this 
but if you have in data-group output not valid json for example : data-groups="nature, city" not data-groups='["nature","city"]' 
you must set delimeter option to ',' not delimiter so pls read one more my first comment and dont waste my time again

**Comment by Vestride** [comment]
> pls read one more my first comment and dont waste my time again

people like you are open source sucks
