### ISSUE TITLE
Do you have a vanilla distribution of Shuffle which can be used directly in a <script> tag?

### ISSUE THREAD

**Issue by bit-pax** [Vestride/Shuffle#558]
I'd like to use Shuffle with a simple static website. Not sure how to go about it though?

**Comment by Vestride** [comment]
You can use unpkg or another npm distributor <https://unpkg.com/shufflejs>, though I do recommend using a bundler and not loading directly from a CDN.

**Comment by bit-pax** [comment]
Thank you! I'll go try it out! :)
