### ISSUE TITLE
Not a bug - Is there a way to have it update positions when browser resizing is finished?

### ISSUE THREAD

**Issue by bit-pax** [Vestride/Shuffle#559]
I noticed it will try to reposition items while the browser is being resized. I was wondering if there's an option for it to only resize when the browser resizing is done?

**Comment by Vestride** [comment]
No, there isn’t a way to disable that. Though you could modify the private resize observer property if you really wanted to

https://github.com/Vestride/Shuffle/blob/ecc4d8a57d95c770feae66df2488fe4f5d4f03bc/packages/shuffle/src/shuffle.js#L1009-L1012
