### ISSUE TITLE
How to wait until items are removed?

### ISSUE THREAD

**Issue by xianoss** [Vestride/Shuffle#57]
Hi, I'm using shuffle.js for presenting search results. What I need is to clear grid and present new results after each search. How can I wait with adding items until items are removed after mygrid.shuffle('remove', items) ? I know we have "removed" callback but when I add new items in this callback, in some situations grid is broken(for example when items adding animation is not finished, then after clearing grid and calling add in "remove" callback, some of old items stays there, but invisible).  How it should be done?

**Comment by xianoss** [comment]
falstart, didn't noticed "removed" callback, please delete this issue:)

**Comment by Vestride** [comment]
I have not tried removing then immediately adding more items.
Please read the [contributing](https://github.com/Vestride/Shuffle/blob/master/CONTRIBUTING.md#submitting-issues) information and provide a reduced test case if you would like me to take a look at it.
