### ISSUE TITLE
Problem when animating the instanced element

### ISSUE THREAD

**Issue by sabarasaba** [Vestride/Shuffle#58]
When I animate the instanced element with a width transition the items of the grid are not being updated.

Here's a working example:

http://jsbin.com/seqesorato/1/edit?js,output

PS: Make sure that the output window is at least 800px

Thanks,
Ignacio.

**Comment by Vestride** [comment]
Updating it once the transition finishes works for me. http://jsbin.com/layifi/1/edit?js,output

```js
$('.filters').toggleClass('col-sm-0 col-sm-4').on('transitionend', function() {
  $grid.shuffle('update');
});
```
