### ISSUE TITLE
Is there a way to make shufflejs have equal heights for all cells (leaving padding potentially at the bottom)

### ISSUE THREAD

**Issue by atishay811** [Vestride/Shuffle#59]
There are cases where masonry is not required. Just want a clean row column layout where each row can be distinguished easily from the others.

**Comment by Vestride** [comment]
If you want an even row, make them all the same height.

**Comment by DanielZanchi** [comment]
What if my images have different heights?

**Comment by guyvanbael** [comment]
i solved it by adding a functioin which takes the height of each item, filters the highest one and sets the height for all items to this value. function gets called just before the shuffle is executed.
`var setEqualHeightForShuffleItems = function(childItemSelector) {
    //selects all items
    var elements = $(childItemSelector);
    //puts the height of all items in an array
    var heights = elements.map(function (index, element) { return $(element).height(); });
    //gets the highest value out of the array
    var maxHeight = Math.max(...heights);
    //sets height of all the items to be the same as the highest one
    elements.map(function (index, element) { $(element).height(maxHeight); });
}`

**Comment by nathanp** [comment]
Thanks, @guyvanbael that works great for me!
