### ISSUE TITLE
When I modify a "data-groups" tag on-the-fly, how do I get Shuffle to update and account for the changed values?

### ISSUE THREAD

**Issue by torrobinson** [Vestride/Shuffle#60]
See question title - I've tried all the included methods, but when I add or remove a data group from an element's data-groups attribute, Shuffle keeps filtering based on the the original values. How do refresh this, is this possible?

Thanks

**Comment by Vestride** [comment]
Shuffle use's [jQuery's data](http://api.jquery.com/data/) method to retrieve the parsed JSON from the `data-groups` attribute. jQuery only reads the attribute the first time and stores its values.

> The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).

You'll need to also use `.data` to update the element.

```js
$item.data('groups', ['foo', 'bar'])
```
The above should work.

**Comment by torrobinson** [comment]
Holy cow, I was clearly lacking the knowledge for that one... I actually had no idea about the data method! Now I'm able to render the page pre populated with the "groups" data and then modify it on the fly.  Everything is buttery smooth now.

Thanks!

**Comment by Vestride** [comment]
:+1:
