### ISSUE TITLE
Search on multiple elements?

### ISSUE THREAD

**Issue by jgrayillustrate** [Vestride/Shuffle#61]
I'm trying to allow for the ability to search on multiple items/elements concurrently -  I tried simply using concatenation with the documented search functionality, but I'm not sure what's going on behind the scenes in order to debug this.

Example:

    var title = $.trim( $el.find('.episode-title').text() ).toLowerCase();
    var feature = $.trim( $el.find('.episode-feature').text() ).toLowerCase();
    var concat = title+feature;
    return concat.indexOf(val) !== -1;

It's not working as I expected, I can filter down by searching for one element or another, but not both at the same time - I'm trying to achieve a narrowing down effect.

Example items:

<b>Item 1</b>
   Title: Test title 1
   Feature: John Doe

<b>Item 2</b>
   Title: Test title 2
   Feature: John Doe

So, searching for something like "Doe 1" should return 'Item 1'.

Here's a [Fiddle](http://jsfiddle.net/qag8rmfo/1/)

**Comment by Vestride** [comment]
The `indexOf` method for strings only works in sequence.

```js
"test title 1 john doe".indexOf("doe 1"); // -1
```
will not be found.

```js
"test title 1 john doe".indexOf("title 1"); // 5
```

If you want to get fuzzy searching to work, you'll have to add your own library, then return `true` or `false` if the item should be visible or hidden.
