### ISSUE TITLE
Cant get "initialSort" to work...

### ISSUE THREAD

**Issue by rcoull** [Vestride/Shuffle#63]
I have everything working great with shuffle, but cant get the grid to sort on a group on initial load.

I have tried...

$grid.shuffle({ itemSelector: '.profile', initialSort: '["mygroupname"]' });

and

$grid.shuffle({ itemSelector: '.profile', initialSort: 'mygroupname' });

But my grid always just loads showing the first images in order of load, not sorted.

Can you help?

**Comment by Vestride** [comment]
As described in the options:
> Shuffle can be initialized with a sort object. It is the same object given to the sort method.

As described in the [sorting](http://vestride.github.io/Shuffle/#sorting) section:
> The opts parameter can contain two properties. `reverse`, a boolean which will reverse the array. `by` is a function that is passed the element wrapped in jQuery. In the case above, we’re returning the value of the data-date-created or data-title attributes.
>
> Calling sort with an empty object will reset the elements to DOM order.

**Comment by rcoull** [comment]
I read the options, and read the instruction "Shuffle can be initialized with a sort object. It is the same object given to the sort method."

As far as I can tell, doing this:

$grid.shuffle({ itemSelector: '.profile', initialSort: '["mygroupname"]' });

Is following the instructions to "Shuffle can be initialized with a sort object. It is the same object given to the sort method."

But this doesnt work.

Can you please clarify what "Shuffle can be initialized with a sort object. It is the same object given to the sort method." means in terms of code, and tell me what I need to do in my code of "$grid.shuffle({ itemSelector: '.profile', initialSort: '["mygroupname"]' });" to get the "initialSort" parameter to work?

I have read the documents already, but it wasnt clear in terms of a code example using "initialSort", so just repeating the documents doesnt help me any further.

Thanks

**Comment by Vestride** [comment]
The example I linked you to has all the code you require.

```js
$grid.shuffle('sort', opts);
```
And,
> Shuffle can be initialized with a sort object. It is the same object given to the sort method.

Therefore, all you need is to make `initialSort` the same as `opts`.

```js
$grid.shuffle({
  itemSelector: '.profile',
  initialSort: {
    by: function($element) {
      return $element.attr('thing-to-sort-by');
    }
});
```

I maintain this project in my spare time. If you think the documentation is lacking, please submit a pull request. Also, please [learn how to use markdown](https://guides.github.com/features/mastering-markdown/); it will make your comments much easier to read.

**Comment by rcoull** [comment]
Thanks for your time and your reply.

I have initial sort working now.

Your project is really great, and your efforts much appreciated!
