### ISSUE TITLE
Transition end events don't fire with speed: 0

### ISSUE THREAD

**Issue by sampohaavisto** [Vestride/Shuffle#64]
Hello!

Thanks for the great work with Shuffle.

Unfortunately I'm having hard times disabling the animation on V3. When speed is set to 0 it seems that Shuffle won't work more than once.

The reason I want to disable animations is to boost mobile performance.

[Here's](http://jsfiddle.net/LydLrsmx/) a jsFiddle pinpointing the problem.

**Comment by Vestride** [comment]
It's breaks because the `transitionend` event never triggers. You can work around this by using the `supported` option and setting it to `false`, which will use jQuery's `.animate()` method.
