### ISSUE TITLE
Event layout.shuffle is triggered on Shuffle init

### ISSUE THREAD

**Issue by sampohaavisto** [Vestride/Shuffle#65]
Hello again! 

While I'm at it I noticed that event layout.shuffle now triggers on done too.

[Link to jsFiddle](http://jsfiddle.net/L2j996on/).

**Comment by Vestride** [comment]
Yes it does because a layout happened.

**Comment by sampohaavisto** [comment]
Ok, this wasn't happening on v2 I used. Had to have same function run on both events to get desired results.
