### ISSUE TITLE
part of right column overlapped because of COLUMN_THRESHOLD

### ISSUE THREAD

**Issue by andrejsramko** [Vestride/Shuffle#66]
this part causes little problems for me, when I'm trying to resize my window:

```javascript
var calculatedColumns = (containerWidth + gutter) / columnWidth;

  // Widths given from getComputedStyle are not precise enough...
  if ( Math.abs(Math.round(calculatedColumns) - calculatedColumns) < COLUMN_THRESHOLD ) {
    // e.g. calculatedColumns = 11.998876
    calculatedColumns = Math.round( calculatedColumns );
  }

  this.cols = Math.max( Math.floor(calculatedColumns), 1 );

  // in my case NOK:
  // cols:4 containerWidth:925 colWidth:250
  // (75px of the right column covered)
```

The COLUMN_THRESHOLD constant causes that for example this.cols change
from 4 to 3 after the right container border one third of the 4th column overlaps...

Wouldn't it be possible / good to make the COLUM_THRESHOLD adjustable and not constant?

**Comment by Vestride** [comment]
It would. See #46

**Comment by andrejsramko** [comment]
sorry for redundance. I have overseen the issue.

**Comment by Vestride** [comment]
No worries.

On Wednesday, February 25, 2015, andrejsramko <notifications@github.com>
wrote:

> sorry for redundance. I have overseen the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vestride/Shuffle/issues/66#issuecomment-75925228>.
>


-- 
Sent with my thumbs
