### ISSUE TITLE
select picture-item not work

### ISSUE THREAD

**Issue by ardani** [Vestride/Shuffle#67]
hai vestride . i have  problem in selector example this
```html
<div id='grid'>
  <div class='view'>
     <div class='view-content'>
        <div class='picture-item'>
         <!--  code picture thumbnail-->
        </div>
     </div>
     </div>
</div>
```
i declare selector using '.picture-item' inside div shuffle not work. 
my question how to select 'picture-item' in div like code above

**Comment by Vestride** [comment]
Please read the contributing information and provide a reduced test case if you would like me to take a look at it.
