### ISSUE TITLE
There is not enough licensing information

### ISSUE THREAD

**Issue by sohan5005** [Vestride/Shuffle#68]
Hi, I was looking for available jQuery filtering plugins and I found this one. But it doesn't have enough licensing information.

If I want to use it on a premium wordpress theme, am I allowed to use it for free?

* The theme will be uploaded to marketplace for sell.

Thanks

**Comment by Vestride** [comment]
There is a license [right here](https://github.com/Vestride/Shuffle/blob/master/LICENSE).

You may use this plugin for whatever you want, including a premium wordpress theme.
