### ISSUE TITLE
column resizing isn't working

### ISSUE THREAD

**Issue by bfrable** [Vestride/Shuffle#69]
http://dev.buffalonews.com/Brett/thingstodo.buffalonews.com/events/

if you resize the page, you'll see the gutter gets all messed up on window resize. 

Is there anyway to fix this? All I can figure out it setting throttle to NULL - but then I have no control over speed.

Best,

Brett

**Comment by bfrable** [comment]
It even has issues here.

http://vestride.github.io/Shuffle/

**Comment by bfrable** [comment]
Testing in chrome.

**Comment by Vestride** [comment]
I don't see what the issue is. Do you have a test case I can look at?

**Comment by bfrable** [comment]
Happens on screen resize. Really happening on mine. Screenshot of your site attached. Chrome browser. Latest stable version. 

http://dev.buffalonews.com/Brett/thingstodo.buffalonews.com/events/

![screen shot 2015-03-09 at 11 15 42 am](https://cloud.githubusercontent.com/assets/7389822/6557741/b9067ae4-c64d-11e4-97a4-2a36256604d0.png)
