### ISSUE TITLE
A Simple Example

### ISSUE THREAD

**Issue by z3dev** [Vestride/Shuffle#72]
All of your examples use JavaScript libraries that take hours / days / weeks / months to understand.

How about a simple example using just HTML? How about a example that sorts tables, lists, paragraphs, etc.

Come back to earth!

**Comment by Vestride** [comment]
Aside from being rude, I really have no idea what you're talking about. This is a **jQuery** plugin! You need jQuery! Modernizr is included, you don't need to know anything about it. If you're trying to sort tables, you've come to the wrong place.
