### ISSUE TITLE
hide all grid (

### ISSUE THREAD

**Issue by mrolbe** [Vestride/Shuffle#74]
Hi,
in issue #48 someone ask to hide all item on first load.
you said : For hiding the initial load, check out the events section. It has an example of exactly what you want.

or hide all items except one item?

I tried hours and hours but i can't find (the code,  i m sorry a m not developer) and where put this code in the html?.
Could you help me?

thx for the answer

**Comment by mrolbe** [comment]
no one?

**Comment by Vestride** [comment]
To hide all the items in the grid, call the filter method and return false
so that none of them are shown. If you wish to do this on page load,
initialize shuffle then wait for the "done" event to hide them all.

**Comment by mrolbe** [comment]
thx for the answer
but "call the filter method and return false"
it s like chinese for me

can you give me a line code?

**Comment by Vestride** [comment]
There's an example in the docs here
http://vestride.github.io/Shuffle/#advanced-filters. Use the `shuffle`
method and instead of returning the title length less than 10 characters,
simply return `false`.

**Comment by mrolbe** [comment]
<script>
$( document ).ready(function() {
   $('#grid').shuffle('shuffle', function($el, shuffle) {
  return FALSE;
  });
});
</script>


like that?

**Comment by Vestride** [comment]
```js
var $grid = $('#grid');
$grid.shuffle(options);
$grid.on('done.shuffle', function() {
  $grid.shuffle('shuffle', function() {
    return false;
  });
});
```

**Comment by mrolbe** [comment]
Hallelujah,
it works!

**Comment by Vestride** [comment]
You would use the name of the group instead of the function.

```js
var $grid = $('#grid');

$grid.on('done.shuffle', function() {
  $grid.shuffle('shuffle', 'my-group-name);
});

$grid.shuffle(options);
```

**Comment by Vestride** [comment]
Sorry, I forgot about the group option. You can use the `group` option when you initialize shuffle.

```js
var $grid = $('#grid');

$grid.shuffle({
  group: 'my-group'
});

// ---------
// or
// ----------

$grid.shuffle({
  group: function($element) {
    return $element.hasClass('foo');
  }
});
```

**Comment by mrolbe** [comment]
Hi thx for the answer but tried (Tage_2S2 is the name of my group)

var $grid = $('#grid');

$grid.shuffle({
  group: function($Tage_2S2) {
    return $Tage_2S2.hasClass('foo');
  }
});
and 
$grid.shuffle({
  group: 'Tage_2S2'
});

And the two tests didnot  work
