### ISSUE TITLE
Only show a single group

### ISSUE THREAD

**Issue by MomoPT** [Vestride/Shuffle#75]
Hi,

It is possible only show the first group initially? 
In my case I have 3 groups and onLoad page it show me the 3, without filter applied.

thanks

**Comment by Vestride** [comment]
You can use the `group` option when you initialize shuffle.

```js
var $grid = $('#grid');

$grid.shuffle({
  group: 'my-group'
});

// ---------
// or
// ----------

$grid.shuffle({
  group: function($element) {
    return $element.hasClass('foo');
  }
});
```
