### ISSUE TITLE
Preserve DOM order

### ISSUE THREAD

**Issue by arunstan** [Vestride/Shuffle#76]
Is there way the elements are displayed by shuffle respect their order in DOM ?

**Comment by Vestride** [comment]
That's the default behavior if you do not sort them.

**Comment by arunstan** [comment]
Yes I agree, but if you change the height of a particular item, and when it expands it,s shuffle tries to align it in the best possible way which can cause to shift it to right, thereby breaking the order.

**Comment by Vestride** [comment]
To keep the same order, you'll have to make the height of each item the same. The algorithm used to place items looks for the column with the lowest height.

**Comment by arunstan** [comment]
Ah I see, thanks for confirming it. Sadly I had to switch to masonry and use it is companion plugin masonry ordered [http://masonry-ordered.tasuki.org]

Any plans to provide a similar option for shuffle as well ?

**Comment by Vestride** [comment]
Probably not. Glad you found a solution!
