### ISSUE TITLE
Grids Malfunction!

### ISSUE THREAD

**Issue by baig-shariq** [Vestride/Shuffle#77]
Hi,

So, this is the page for portfolio. Right now, the script starts with All data group activated at the start up. I want TV data group to be activated when the page is loaded. I tried doing it and was able to make the page to start with TV data group but some grids were malfunctioning and was not showing the text at all. Need Help. Thanks :)

Page link: http://www.tamashi-themes.com/themes/kineoworks/R2/portfolio.html

**Comment by Vestride** [comment]
Please provide the code you're using to initialize Shuffle.

Next, update the version of Shuffle which you are using, it's almost 2 years old! Side note: where did you find that version? If I am linking to it, I would like to update my links :)

To show only a single group on page load, look at issue #75

**Comment by baig-shariq** [comment]
I have already applied the solution given in issue #75 and it shows a single group fine but the problem starts after that with "ALL" group activated at start up every grid with hover effect was working but after with single group activated some grids are not showing the hover text. I have attached a link to code. Please review it and update me about the problem.

About the version of Shuffle I got it from a theme template so you don't have to worry about that.

Will wait for your solution to this problem. Many thanks.

Download Link:
https://www.dropbox.com/s/e7i3cz1s8c3kl3p/shuffle.rar?dl=0

**Comment by Vestride** [comment]
Please read the contributing guidelines for creating a reduced test case.

**Comment by baig-shariq** [comment]
Can you please elaborate?

**Comment by Vestride** [comment]
https://github.com/Vestride/Shuffle/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by baig-shariq** [comment]
Hey,

Sorry for that. Now I have made a reduced test case. Please review it and help me.

http://codepen.io/anon/pen/BNzgQW
In this when "all" data group is activated at start up everything is working perfectly fine. Every hover effect is working great but then,

http://codepen.io/anon/pen/QbEReg
In this when "tv" data group is activated at start up, the first grid is not showing the hover text in tv and some other data groups and it doesn't resolves unless you go to "all" data group.

**Comment by Vestride** [comment]
Updating to the latest version of Shuffle will fix this issue (as I originally suggested).
