### ISSUE TITLE
Feature: publish laid out items

### ISSUE THREAD

**Issue by ryanjshaw** [Vestride/Shuffle#79]
I'm building an infinite scroll for images and I need to be able to determine which items are visible to do intelligent updates/deletes.

While there are (slow and complicated) methods for determining this independently of the shuffle library (e.g. iterate through entire array of $items and check bounds against viewport), it's much simpler to determine the first/last visible rows and just iterate through the laid out items by calculating the first/last visible index. 

Unfortunately the _layout method doesn't appear to save the filtered/sorted items after they have been computed. I looked at implementing this myself (as a parameter to the LAYOUT event, which fires after movementFinished) but was wondering if there was a scenario this might not work? It looks like the addItems logic already handles the only edge case I can think of (partial changes).

**Comment by Vestride** [comment]
You could use `shuffle.$items.filter('.filtered')` to get the visible items (which is what the `_getFilteredItems` method does), or you could add another property to shuffle like `order` and update that inside the `sort` method.
