### ISSUE TITLE
First call pile up images

### ISSUE THREAD

**Issue by Giugiur** [Vestride/Shuffle#80]
Hi, I can't get my grid to work properly. As you can see here: http://gbetonline.com/app/#/bets on the first call the images pile up in the first row. But, if you press f5 it works just fine, is in the first call only in all browsers and with clean cache. Here's some code, I'm using Angularjs, and Bootstrap 3:

https://jsfiddle.net/ov8fmea7/1/
     
.filter img is a class for sortering purposes which works just fine and I didn't include that because I don't think the problem is there.

**Comment by Vestride** [comment]
Try this http://vestride.github.io/Shuffle/images/

**Comment by Giugiur** [comment]
Neither of those 3 worked for me. Height is not the issue, as in the first call they pile up, but in the second call and thereafter they get the height I assigned to 'item', but doesn't solve the issue. 
The plugin didn't affect at all to what is happening. No changes.

Here's on the first call: http://puu.sh/icr4v/2add1f5b87.jpg
Here's after reload and thereafter (if I close the page and reopen, we go back to the first call): http://puu.sh/icr5N/61a844e2b6.jpg

Forgot to mention, the grid is loaded using AJAX. The images are in local files but their src and the rest of the DOM is loaded via a GET call.

**Comment by Vestride** [comment]
Height *is* the issue. The fourth and fifth items are stacked on top of the first and second items because their height depends on the height of the image. See my comment in #78 for how to create aspect ratio boxes. I think this will solve your issue. You'll notice that once your resize your window or click on the filters, the items are laid out correctly because the images had loaded.

**Comment by Giugiur** [comment]
I used the code you wrote in #78 and that it did the trick! Thank you so much I wasted a tremendous amount of time with this, now I'm happy to see it solved.
Btw, let me tell you I love your plugin is my favorite! Great work.
