### ISSUE TITLE
Images with different width/heigth 

### ISSUE THREAD

**Issue by danielgmarcos** [Vestride/Shuffle#81]
Hi. First of all thanks for putting some effort on this, is really helpful. 

I cannot shuffle images with different sizes.
Is there anything I'm missing? Is this supported? 

I mean something like this:

![screen shot 2015-06-10 at 19 10 10](https://cloud.githubusercontent.com/assets/5120207/8090183/5d0297d2-0fa4-11e5-83f3-617330612011.png)

Cheers

**Comment by Vestride** [comment]
It is supported, as you can see on the home page for Shuffle.
