### ISSUE TITLE
Remove shuffle items when there are not items

### ISSUE THREAD

**Issue by mbeneyto** [Vestride/Shuffle#83]
Hi, first of all thanks for this awesome and powerfull jQuery plugin. 

I'm doing some tests and I've seeing that when I'm doing $('#shuffle').shuffle('remove', $remove) and $remove is empty (shuffle has not any item attached), 'remove' event is not fired. Is this behavior correct?

Thanks.

**Comment by Vestride** [comment]
Yes, this is the correct behavior.

From the source:

```js
if ( !$collection.length || !$collection.jquery ) {
  return;
}
```
