### ISSUE TITLE
RTL support, layout modes

### ISSUE THREAD

**Issue by webmandesign** [Vestride/Shuffle#86]
Hi, 

Is there an RTL support in the script? Something like http://isotope.metafizzy.co/v1/tests/right-to-left.html

Also, does the script support different layout modes, like Isotope: http://isotope.metafizzy.co/layout-modes.html (specifically I'm interested in http://isotope.metafizzy.co/layout-modes/fitrows.html)?

Thanks for the answers!

Regards,

Oliver

**Comment by Vestride** [comment]
Nope, there is no support for RTL nor different layout modes. If you require those, isotope is probably what you want.

**Comment by webmandesign** [comment]
Hi,

That's really unfortunate, but thank you for the answer. I wanted to use Shuffle instead of Isotope due to it's 100% GPL.

Regards,

Oliver
