### ISSUE TITLE
How to check if there are no items in $collection after a shuffle

### ISSUE THREAD

**Issue by Giugiur** [Vestride/Shuffle#88]
Hi, I have using this plugin with no problems, but now I want to add a functionality and I need to know when the user filters if there are no items that matches the criteria:

    var $grid = $('#grid');
        $grid.shuffle({
            itemSelector: '.item',         
        }); 
        $('.filters img').click(function (e) {  
            var groupName = $(this).attr('data-group');                     
            $grid.shuffle('shuffle', groupName);
            $grid.on('layout.shuffle', function( evt, $collection, shuffle ) {
            if ($collection.visibleItems >=1) {
                //do something
            }
            else {
                // do another something
            }
          });
The thing is I have been looking around and found layout.shuffle but it doesnt accomplish what I want to do. Also, done.shuffle works but only on first call (the setup), then it doesn't behave as I want. Tried to move the $grid.on bit around (in and out, etc) but with no effect. 
My objective is to know in the moment when the grid is done shuffling, how many visible items are in the collection, specially if there are no items visible after the filter was applied.

**Comment by Vestride** [comment]
Try `shuffle.visibleItems`?

**Comment by Giugiur** [comment]
Yup, I get Uncaught TypeError: Cannot read property 'visibleItems' of undefined

**Comment by Vestride** [comment]
@Giugiur did you resolve this?

**Comment by Giugiur** [comment]
I'm using a hotfix based on jQuery and a loop but is not the ideal solution. In other words, I didn't resolve this. Have you any suggestion?

**Comment by Vestride** [comment]
`shuffle` in your event listener shouldn't be `undefined`. If I set a breakpoint on the [homepage](https://github.com/Vestride/Shuffle/blob/master/js/demos/homepage.js#L21) demo JavaScript, `shuffle` is defined for me.

```js
$('#grid').on('layout.shuffle', function(evt, shuffle) {
  console.log(shuffle.visibleItems);
});
```

**Comment by Giugiur** [comment]
Yes, this doesnt work all times. When there are no items visible, shuffle.visibleItems returns nothing. I mean, literally nothing, can't even compare it to a value or a condition when there are no items visible :/

**Comment by Vestride** [comment]
Not sure what to tell you, it always works for me.

**Comment by Giugiur** [comment]
Console returns 0 when there are no visible items? Mine doesn't. Gonna use the "bad" solution until I can think of something else. Thanks anyway for your help.

**Comment by Vestride** [comment]
Yep. If I visit the homepage for Shuffle and enter these into the console, it logs `0`.

```js
$('#grid').on('layout.shuffle', function(evt, shuffle) {
  console.log(shuffle.visibleItems);
});

$('#grid').shuffle('shuffle', 'foo');
```
