### ISSUE TITLE
Default for items with no groups

### ISSUE THREAD

**Issue by Doff3n** [Vestride/Shuffle#89]
Shuffle.prototype._doesPassFilter
should have 
    ```if(groups==null)
      return false;
     ```
In case the item does not have any groups(And therefore should be filtered out)

**Comment by Vestride** [comment]
```javasscript
$.inArray('foo', undefined) > -1
```

Still evaluates to false, so unless you have a custom delimeter and the element doesn't have a `data-groups='[]'` attribute, it will behave as expected.

What's your use case for this?
