### ISSUE TITLE
[Feature] Why not vanilla JS?

### ISSUE THREAD

**Issue by thednp** [Vestride/Shuffle#91]
I like this script, I think it's great to the point of jQuery plugin.

Any plans?

**Comment by Vestride** [comment]
I don't have any plans currently for it, but I'm not against it. I
originally wrote this a few years ago and it needed to support IE7 and some
other awful browsers. I think it would be great to rewrite it in ES6 and
transpile to ES5 while dropping support for many browsers.

But for right now, I'm not willing to invest that much time in it.

**Comment by thednp** [comment]
Thanks for the reply. I'll keep my eyes on it.
