### ISSUE TITLE
shuffle("remove") doesn't work properly if it is issued concurrently with shuffle("appended")

### ISSUE THREAD

**Issue by MayamaTakeshi** [Vestride/Shuffle#93]
Sample:
https://jsfiddle.net/u1kh663r/1/

Notice how the items abruptly disappear instead of easing out. The only one that eases out properly is the last one because no more "appended" requests are being issued.
Then, just changing the TIME_TO_LIVE of the items to a value that will not coincide with "appended" requests makes all of them ease out properly:
https://jsfiddle.net/u1kh663r/2/

**Comment by Vestride** [comment]
Closing as won't fix for Shuffle 3. If this is still an issue with Shuffle 4, let me know and I'll look into it.
