### ISSUE TITLE
No prepend ?

### ISSUE THREAD

**Issue by ntom** [Vestride/Shuffle#96]
There is no prepend ? Like.. new data cannot feed in to the start of the grid ?

**Comment by Vestride** [comment]
Nope, you can only append them, append with a delay, or add them in with the current filter applied.

http://vestride.github.io/Shuffle/adding-removing/

**Comment by Vestride** [comment]
You can now prepend items with v4. Check out the [demo](https://vestride.github.io/Shuffle/adding-removing) again. Shuffle will now maintain the DOM sorting order when new items are added, so if you prepend them, they will show up at the top of the grid.
