### ISSUE TITLE
Images overlapping each other, other divs. 

### ISSUE THREAD

**Issue by cstevensd** [Vestride/Shuffle#97]
I have this script running, and find that sometimes, in all browsers, the images overlap each other when first entering page with them in it. Weird thing is, if you reload, or resize window it recalibrates itself.

Please help!

**Comment by Vestride** [comment]
http://vestride.github.io/Shuffle/images/
http://vestride.github.io/Shuffle/image-problems/
http://vestride.github.io/Shuffle/faq/

**Comment by FernandoDWG** [comment]
Hello, I have the same problem.
On Firefox all goes almost right (the vertical space bettween rows is greater than I would like when the page loads, but when I clic a button for filtering, it goes right.
On Chrome the images overlap eachs other and my footer. When I clic a button for filtering, it goes right.
I've tried to use the URL you said, but there are not operative (404 error).
Thanks a lot
Fernando
My testing
![shuffle-js-overlapping-error-on-chrome](https://cloud.githubusercontent.com/assets/22198861/18519407/2096bca8-7aa4-11e6-8489-b943ab72d6e2.png)
 URL is: http://www.xn--diseowebglobal-tnb.es/websdwg/dwg/agencia/portfolio-diseno-web-salamanca.php

**Comment by Vestride** [comment]
Links updated. Thanks for letting me know.
