### ISSUE TITLE
Mixing layout and component styles

### ISSUE THREAD

**Issue by cameronroe** [Vestride/Shuffle#99]
Nice plugin! However, I see the example is mixing layout styles and item styles. It's not a good practice to put the element class `.picture-element` directly on the column class `.col-sm-4` because it's then hard to maintain the component and use it in other places. As it should be be only a tag with a class spanning 100% width. I was having trouble with the plugin when writing my code this way. Is it possible to structure the code however you want and just replace the elements that way? Thanks!

**Comment by Vestride** [comment]
I disagree with you, but why not use your component at 100% width as the only child of a `shuffle-item`? Something like:

```html
<div id="grid">
  <div class="col-sm-4 item">
    <div class="my-component-that-is-100-percent-width"></div>
  </div>
  <div class="col-sm-4 item">
    <div class="my-component-that-is-100-percent-width"></div>
  </div>
  <div class="col-sm-4 item">
    <div class="my-component-that-is-100-percent-width"></div>
  </div>
</div>
```

**Comment by cameronroe** [comment]
Typically cols are related to a grid system that's being leveraged across the entire site (aka global). When putting cols on the item itself, you're mixing the item-specific styles which should not contain floats and col widths. The item should be decoupled with it's own styling. Technically the col is just a spanned width of the page that should then contain elements.

**Comment by Vestride** [comment]
I understood your opinion the first time and I still disagree with it.

If I were to separate layout styles from visual ones, each item in the grid would need an inner item nested  within it. People already struggle to implement shuffle and I don't want to make it any harder than it needs to be.

You are completely free to style elements inside the "item" any way you see fit.

**Comment by cameronroe** [comment]
Honestly, I would do without the grid completely for the example, but no worries either way.
